-- 001_tenant.sql — <TENANT_NAME>
-- Vertical: <VERTICAL_ID> | Plan: <TENANT_PLAN>
-- Address: <ADDRESS_LINE1>, <CITY>, <POSTAL_CODE>, <COUNTRY_CODE>
-- Currency: <PRIMARY_CURRENCY>
--
-- NOTE: <TENANT_NAME> must be unique across the platform. Since migration
-- 015 a case-insensitive UNIQUE index (tenants_name_ci_unique) enforces
-- this at the DB layer, so duplicate loads fail fast with
-- "duplicate key value violates unique constraint". The precheck below
-- stays in place as defense in depth — it gives a clearer error before
-- a long seed transaction starts:
--   SELECT name FROM tenants WHERE lower(trim(name)) = lower(trim('<TENANT_NAME>'));
--
-- See seeds/template/new-tenant/README.md for what each <PLACEHOLDER>
-- means and how to fill it in. This file scaffolds:
--
--   1. The cross-tenant tenants row.
--   2. The tenant_verticals binding so vertical-aware services know
--      which YAML config to load.
--   3. The seven system roles (super_admin, manager, coordinator,
--      accountant, member, inventory_manager, project_supervisor) —
--      mirrors iam.Service.seedSystemRoles, with role UUIDs generated
--      by the database so the operator does not have to pick them.
--
-- Run order: this file first, then 002_admin_user.sql.

-- ──────────────────────────────────────────────────────────────────
-- 1. Tenant row
-- ──────────────────────────────────────────────────────────────────

INSERT INTO tenants (
    id, name, slug, plan, status,
    address_line1, address_line2, city, country_code, postal_code,
    primary_currency_code
) VALUES (
    '<TENANT_UUID>',
    '<TENANT_NAME>',
    '<TENANT_SLUG>',
    '<TENANT_PLAN>',
    'active',
    '<ADDRESS_LINE1>',
    <ADDRESS_LINE2>,            -- quoted string 'line 2' OR bare keyword NULL
    '<CITY>',
    '<COUNTRY_CODE>',
    '<POSTAL_CODE>',
    '<PRIMARY_CURRENCY>'
)
ON CONFLICT (id) DO NOTHING;

-- ──────────────────────────────────────────────────────────────────
-- 2. Vertical binding
-- ──────────────────────────────────────────────────────────────────
-- registered_by forward-references the admin user that 002_admin_user.sql
-- will insert. The user row does not exist yet, but tenant_verticals
-- does not FK registered_by, so the forward reference is fine.

INSERT INTO tenant_verticals (tenant_id, vertical_id, registered_by) VALUES
    ('<TENANT_UUID>',
     '<VERTICAL_ID>',
     '<ADMIN_USER_UUID>')
ON CONFLICT (tenant_id) DO NOTHING;

-- ──────────────────────────────────────────────────────────────────
-- 3. System roles (idempotent on (tenant_id, name))
-- ──────────────────────────────────────────────────────────────────
-- Role UUIDs are generated by the DB. 002_admin_user.sql looks them up
-- by name — never hardcode a role UUID across tenants.

INSERT INTO roles (tenant_id, name, permissions, is_system) VALUES
    ('<TENANT_UUID>', 'super_admin',
     ARRAY['production:read','production:write',
           'budget:read','budget:write','budget:approve',
           'expense:submit','expense:approve',
           'inventory:checkout',
           'report:read',
           'user:manage'],
     true),
    ('<TENANT_UUID>', 'manager',
     ARRAY['production:read','production:write',
           'budget:read','budget:approve',
           'expense:approve',
           'inventory:checkout',
           'report:read'],
     true),
    ('<TENANT_UUID>', 'coordinator',
     ARRAY['production:read','production:write',
           'budget:read','budget:write',
           'expense:approve',
           'inventory:checkout',
           'report:read'],
     true),
    ('<TENANT_UUID>', 'accountant',
     ARRAY['budget:read',
           'expense:submit','expense:approve',
           'report:read'],
     true),
    ('<TENANT_UUID>', 'member',
     ARRAY['production:read',
           'expense:submit'],
     true),
    ('<TENANT_UUID>', 'inventory_manager',
     ARRAY['inventory:read','inventory:write',
           'inventory:checkout','inventory:retire'],
     true),
    ('<TENANT_UUID>', 'project_supervisor',
     ARRAY['production:read',
           'budget:read',
           'expense:submit','expense:approve',
           'resource:manage',
           'inventory:checkout'],
     true)
ON CONFLICT (tenant_id, name) DO NOTHING;
