"""Tests for tenant_onboard.vertical — CoA checks and migration rendering."""

import copy
import json
import re

import pytest

from tenant_onboard.errors import Issue, ValidationError, VerticalConfigError
from tenant_onboard.vertical import parse_vertical, render_migration


def _fields(exc: VerticalConfigError) -> list[str]:
    return [i.field for i in exc.issues]


class TestLoad:
    def test_meta(self, vertical):
        assert (vertical.id, vertical.name, vertical.version) == ("test-studio", "Test Studio", "0.0.1")

    def test_description_is_folded_to_one_line(self, vertical):
        assert "\n" not in vertical.description
        assert vertical.description.startswith("Mock vertical")

    def test_config_excludes_meta_but_keeps_everything_else(self, vertical):
        assert not {"id", "name", "version", "description"} & vertical.config.keys()
        assert {"phase_types", "expense_categories", "default_chart_of_accounts"} <= vertical.config.keys()

    def test_accounts_in_declared_order(self, vertical):
        assert [a.code for a in vertical.accounts] == ["1000", "1010", "3000", "4000", "6000", "6100"]
        assert vertical.accounts[1].parent_code == "1000"

    def test_stage_ids(self, vertical):
        assert vertical.stage_ids == ("discovery", "build", "launched")


class TestValidation:
    def test_missing_vertical_key(self):
        with pytest.raises(VerticalConfigError) as ei:
            parse_vertical({"other": {}})
        assert _fields(ei.value) == ["vertical"]

    def test_child_before_parent(self, vertical_dict):
        coa = vertical_dict["vertical"]["default_chart_of_accounts"]
        coa[0], coa[1] = coa[1], coa[0]  # 1010 now precedes its parent 1000
        with pytest.raises(VerticalConfigError, match="defined earlier"):
            parse_vertical(vertical_dict)

    def test_duplicate_code(self, vertical_dict):
        coa = vertical_dict["vertical"]["default_chart_of_accounts"]
        coa.append(copy.deepcopy(coa[0]))
        with pytest.raises(VerticalConfigError, match="duplicate account code"):
            parse_vertical(vertical_dict)

    def test_unquoted_numeric_code(self, vertical_dict):
        vertical_dict["vertical"]["default_chart_of_accounts"][0]["code"] = 1000
        with pytest.raises(VerticalConfigError, match="quote numeric codes"):
            parse_vertical(vertical_dict)

    def test_bad_account_type(self, vertical_dict):
        vertical_dict["vertical"]["default_chart_of_accounts"][2]["account_type"] = "capital"
        with pytest.raises(VerticalConfigError, match="account_type"):
            parse_vertical(vertical_dict)

    def test_parent_type_mismatch(self, vertical_dict):
        vertical_dict["vertical"]["default_chart_of_accounts"][5]["parent_code"] = "1000"
        with pytest.raises(VerticalConfigError, match="parent '1000' is asset, child is expense"):
            parse_vertical(vertical_dict)

    def test_bad_id(self, vertical_dict):
        vertical_dict["vertical"]["id"] = "Test_Studio"
        with pytest.raises(VerticalConfigError, match="lowercase"):
            parse_vertical(vertical_dict)

    def test_reports_all_issues_at_once(self, vertical_dict):
        v = vertical_dict["vertical"]
        del v["name"]
        v["phase_types"] = []
        v["default_chart_of_accounts"][0]["account_type"] = "nope"
        with pytest.raises(VerticalConfigError) as ei:
            parse_vertical(vertical_dict, source="mock.yaml")
        fields = _fields(ei.value)
        assert "vertical.name" in fields
        assert "vertical.phase_types" in fields
        assert any(f.endswith("[0].account_type") for f in fields)
        assert str(ei.value).startswith("mock.yaml:")

    def test_validation_error_requires_issues(self):
        with pytest.raises(ValueError):
            ValidationError("x", [])

    def test_issue_str(self):
        assert str(Issue("a.b", "bad")) == "a.b: bad"


class TestMigration:
    def test_up_is_idempotent_upsert(self, vertical):
        up, _ = render_migration(vertical, "fixtures/vertical_minimal.yaml")
        assert "INSERT INTO vertical_definitions" in up
        assert "ON CONFLICT (id) DO UPDATE" in up
        assert "GENERATED by tools/tenant-onboard from fixtures/vertical_minimal.yaml" in up

    def test_config_json_round_trips(self, vertical):
        up, _ = render_migration(vertical, "x.yaml")
        m = re.search(r"\n    '(\{.*\})'::jsonb,\n", up, re.DOTALL)
        assert m, up
        config = json.loads(m.group(1).replace("''", "'"))
        assert config == vertical.config
        names = [a["name"] for a in config["default_chart_of_accounts"]]
        assert "Owner's Capital" in names and 'Checking — "Main"' in names

    def test_down_deletes_by_id(self, vertical):
        _, down = render_migration(vertical, "x.yaml")
        assert "DELETE FROM vertical_definitions WHERE id = 'test-studio';" in down

    def test_deterministic(self, vertical):
        assert render_migration(vertical, "x.yaml") == render_migration(vertical, "x.yaml")
