// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DunningAttempt struct {
	ID              uuid.UUID   `json:"id"`
	InvoiceID       uuid.UUID   `json:"invoice_id"`
	AttemptNumber   int32       `json:"attempt_number"`
	Outcome         string      `json:"outcome"`
	GatewayResponse pgtype.Text `json:"gateway_response"`
	AttemptedAt     time.Time   `json:"attempted_at"`
}

type Invitation struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Email     string      `json:"email"`
	RoleID    pgtype.UUID `json:"role_id"`
	Token     string      `json:"token"`
	Status    string      `json:"status"`
	InvitedBy uuid.UUID   `json:"invited_by"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
}

type Invoice struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	SubscriptionID uuid.UUID          `json:"subscription_id"`
	InvoiceNumber  string             `json:"invoice_number"`
	Amount         pgtype.Numeric     `json:"amount"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	Currency       string             `json:"currency"`
	Status         string             `json:"status"`
	DueDate        pgtype.Date        `json:"due_date"`
	PeriodStart    time.Time          `json:"period_start"`
	PeriodEnd      time.Time          `json:"period_end"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type PlatformImpersonationLog struct {
	ID               uuid.UUID          `json:"id"`
	PlatformUserID   uuid.UUID          `json:"platform_user_id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	ImpersonatedUser uuid.UUID          `json:"impersonated_user"`
	Reason           string             `json:"reason"`
	StartedAt        time.Time          `json:"started_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	IpAddress        pgtype.Text        `json:"ip_address"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

type PlatformUser struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	MfaSecret    pgtype.Text        `json:"mfa_secret"`
	MfaEnabled   bool               `json:"mfa_enabled"`
	Status       string             `json:"status"`
	CreatedAt    time.Time          `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
	IsSystem    bool      `json:"is_system"`
}

type Subscription struct {
	ID                 uuid.UUID `json:"id"`
	TenantID           uuid.UUID `json:"tenant_id"`
	Plan               string    `json:"plan"`
	Status             string    `json:"status"`
	BillingCycle       string    `json:"billing_cycle"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type Tenant struct {
	ID                  uuid.UUID          `json:"id"`
	Name                string             `json:"name"`
	Slug                string             `json:"slug"`
	Plan                string             `json:"plan"`
	Status              string             `json:"status"`
	CreatedAt           time.Time          `json:"created_at"`
	IsDemo              bool               `json:"is_demo"`
	AddressLine1        pgtype.Text        `json:"address_line1"`
	AddressLine2        pgtype.Text        `json:"address_line2"`
	City                pgtype.Text        `json:"city"`
	CountryCode         string             `json:"country_code"`
	PostalCode          pgtype.Text        `json:"postal_code"`
	PrimaryCurrencyCode string             `json:"primary_currency_code"`
	SuspendedAt         pgtype.Timestamptz `json:"suspended_at"`
	DeactivatedAt       pgtype.Timestamptz `json:"deactivated_at"`
	HoldUntil           pgtype.Timestamptz `json:"hold_until"`
	FreezeReason        pgtype.Text        `json:"freeze_reason"`
	PurgedAt            pgtype.Timestamptz `json:"purged_at"`
}

type TenantAuthConfig struct {
	TenantID         uuid.UUID   `json:"tenant_id"`
	AuthMethod       string      `json:"auth_method"`
	IssuerUrl        pgtype.Text `json:"issuer_url"`
	ClientID         pgtype.Text `json:"client_id"`
	ClientSecretEnc  pgtype.Text `json:"client_secret_enc"`
	Scopes           []string    `json:"scopes"`
	EmailClaim       string      `json:"email_claim"`
	DisplayNameClaim string      `json:"display_name_claim"`
	GroupsClaim      pgtype.Text `json:"groups_claim"`
	AutoProvision    bool        `json:"auto_provision"`
	DefaultRole      string      `json:"default_role"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type TenantPurgeRequest struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	Status        string             `json:"status"`
	RequestedBy   uuid.UUID          `json:"requested_by"`
	RequestedAt   time.Time          `json:"requested_at"`
	RequestReason string             `json:"request_reason"`
	ApprovedBy    pgtype.UUID        `json:"approved_by"`
	ApprovedAt    pgtype.Timestamptz `json:"approved_at"`
	CancelledBy   pgtype.UUID        `json:"cancelled_by"`
	CancelledAt   pgtype.Timestamptz `json:"cancelled_at"`
	ExecutedAt    pgtype.Timestamptz `json:"executed_at"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	TenantName    string             `json:"tenant_name"`
	TenantSlug    string             `json:"tenant_slug"`
}

type TenantSetting struct {
	TenantID      uuid.UUID   `json:"tenant_id"`
	ThemeOverride []byte      `json:"theme_override"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	FaviconUrl    pgtype.Text `json:"favicon_url"`
	UpdatedAt     time.Time   `json:"updated_at"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserRole struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	AssignedBy uuid.UUID   `json:"assigned_by"`
	AssignedAt time.Time   `json:"assigned_at"`
	ProjectID  pgtype.UUID `json:"project_id"`
}
