// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (id, tenant_id, subscription_id, invoice_number, amount, tax_amount, currency, status, due_date, period_start, period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, tenant_id, subscription_id, invoice_number, amount, tax_amount, currency, status, due_date, period_start, period_end, paid_at, created_at
`

type CreateInvoiceParams struct {
	ID             uuid.UUID      `json:"id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	SubscriptionID uuid.UUID      `json:"subscription_id"`
	InvoiceNumber  string         `json:"invoice_number"`
	Amount         pgtype.Numeric `json:"amount"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	Currency       string         `json:"currency"`
	Status         string         `json:"status"`
	DueDate        pgtype.Date    `json:"due_date"`
	PeriodStart    time.Time      `json:"period_start"`
	PeriodEnd      time.Time      `json:"period_end"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ID,
		arg.TenantID,
		arg.SubscriptionID,
		arg.InvoiceNumber,
		arg.Amount,
		arg.TaxAmount,
		arg.Currency,
		arg.Status,
		arg.DueDate,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.TaxAmount,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one

INSERT INTO subscriptions (id, tenant_id, plan, status, billing_cycle, current_period_start, current_period_end)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id) DO NOTHING
RETURNING id, tenant_id, plan, status, billing_cycle, current_period_start, current_period_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID                 uuid.UUID `json:"id"`
	TenantID           uuid.UUID `json:"tenant_id"`
	Plan               string    `json:"plan"`
	Status             string    `json:"status"`
	BillingCycle       string    `json:"billing_cycle"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
}

// Billing service queries.
// subscriptions, invoices, payments, plan_limits live in the shared (public) schema
// since billing is cross-tenant (the billing service manages tenant-level data).
func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.TenantID,
		arg.Plan,
		arg.Status,
		arg.BillingCycle,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.Status,
		&i.BillingCycle,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDunningAttemptCount = `-- name: GetDunningAttemptCount :one
SELECT COUNT(*) FROM dunning_attempts WHERE invoice_id = $1 AND outcome = 'failed'
`

func (q *Queries) GetDunningAttemptCount(ctx context.Context, invoiceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getDunningAttemptCount, invoiceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, tenant_id, subscription_id, invoice_number, amount, tax_amount, currency, status, due_date, period_start, period_end, paid_at, created_at FROM invoices WHERE id = $1 AND tenant_id = $2
`

type GetInvoiceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetInvoice(ctx context.Context, arg GetInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, arg.ID, arg.TenantID)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.TaxAmount,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, tenant_id, plan, status, billing_cycle, current_period_start, current_period_end, created_at, updated_at FROM subscriptions WHERE tenant_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, tenantID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, tenantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.Status,
		&i.BillingCycle,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInvoices = `-- name: ListInvoices :many
SELECT id, tenant_id, subscription_id, invoice_number, amount, tax_amount, currency, status, due_date, period_start, period_end, paid_at, created_at FROM invoices
WHERE tenant_id = $1 AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListInvoicesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListInvoices(ctx context.Context, arg ListInvoicesParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoices,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SubscriptionID,
			&i.InvoiceNumber,
			&i.Amount,
			&i.TaxAmount,
			&i.Currency,
			&i.Status,
			&i.DueDate,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDunningAttempt = `-- name: RecordDunningAttempt :one
INSERT INTO dunning_attempts (id, invoice_id, attempt_number, outcome, gateway_response)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, attempt_number, outcome, gateway_response, attempted_at
`

type RecordDunningAttemptParams struct {
	ID              uuid.UUID   `json:"id"`
	InvoiceID       uuid.UUID   `json:"invoice_id"`
	AttemptNumber   int32       `json:"attempt_number"`
	Outcome         string      `json:"outcome"`
	GatewayResponse pgtype.Text `json:"gateway_response"`
}

func (q *Queries) RecordDunningAttempt(ctx context.Context, arg RecordDunningAttemptParams) (DunningAttempt, error) {
	row := q.db.QueryRow(ctx, recordDunningAttempt,
		arg.ID,
		arg.InvoiceID,
		arg.AttemptNumber,
		arg.Outcome,
		arg.GatewayResponse,
	)
	var i DunningAttempt
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AttemptNumber,
		&i.Outcome,
		&i.GatewayResponse,
		&i.AttemptedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices SET status = $3, paid_at = CASE WHEN $3 = 'paid' THEN now() ELSE paid_at END
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, subscription_id, invoice_number, amount, tax_amount, currency, status, due_date, period_start, period_end, paid_at, created_at
`

type UpdateInvoiceStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.TenantID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SubscriptionID,
		&i.InvoiceNumber,
		&i.Amount,
		&i.TaxAmount,
		&i.Currency,
		&i.Status,
		&i.DueDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.PaidAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscriptions
SET plan                  = $2,
    current_period_start  = $3,
    current_period_end    = $4,
    updated_at            = now()
WHERE tenant_id = $1
RETURNING id, tenant_id, plan, status, billing_cycle, current_period_start, current_period_end, created_at, updated_at
`

type UpdateSubscriptionPlanParams struct {
	TenantID           uuid.UUID `json:"tenant_id"`
	Plan               string    `json:"plan"`
	CurrentPeriodStart time.Time `json:"current_period_start"`
	CurrentPeriodEnd   time.Time `json:"current_period_end"`
}

func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan,
		arg.TenantID,
		arg.Plan,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.Status,
		&i.BillingCycle,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions SET status = $2, updated_at = now()
WHERE tenant_id = $1
RETURNING id, tenant_id, plan, status, billing_cycle, current_period_start, current_period_end, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.TenantID, arg.Status)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Plan,
		&i.Status,
		&i.BillingCycle,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
