// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RegistrationSaga struct {
	ID                 uuid.UUID       `json:"id"`
	Email              string          `json:"email"`
	TenantID           pgtype.UUID     `json:"tenant_id"`
	UserID             pgtype.UUID     `json:"user_id"`
	Status             string          `json:"status"`
	CompletedSteps     json.RawMessage `json:"completed_steps"`
	FailedStep         pgtype.Text     `json:"failed_step"`
	FailureReason      pgtype.Text     `json:"failure_reason"`
	CompensationErrors json.RawMessage `json:"compensation_errors"`
	Request            json.RawMessage `json:"request"`
	CreatedAt          time.Time       `json:"created_at"`
	UpdatedAt          time.Time       `json:"updated_at"`
}

type TenantVertical struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	VerticalID     string    `json:"vertical_id"`
	ConfigOverride []byte    `json:"config_override"`
	RegisteredAt   time.Time `json:"registered_at"`
	RegisteredBy   uuid.UUID `json:"registered_by"`
}

type VerticalDefinition struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Version     string          `json:"version"`
	Description pgtype.Text     `json:"description"`
	Config      json.RawMessage `json:"config"`
	IsActive    bool            `json:"is_active"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
