// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type VerticalDefinition struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Version     string          `json:"version"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
	IsActive    bool            `json:"is_active"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type TenantVertical struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	VerticalID     string          `json:"vertical_id"`
	ConfigOverride json.RawMessage `json:"config_override"`
	RegisteredAt   time.Time       `json:"registered_at"`
	RegisteredBy   uuid.UUID       `json:"registered_by"`
}
