// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const bindTenantVertical = `-- name: BindTenantVertical :exec
INSERT INTO tenant_verticals (tenant_id, vertical_id, config_override, registered_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id) DO NOTHING
`

type BindTenantVerticalParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	VerticalID     string    `json:"vertical_id"`
	ConfigOverride []byte    `json:"config_override"`
	RegisteredBy   uuid.UUID `json:"registered_by"`
}

func (q *Queries) BindTenantVertical(ctx context.Context, arg BindTenantVerticalParams) error {
	_, err := q.db.Exec(ctx, bindTenantVertical,
		arg.TenantID,
		arg.VerticalID,
		arg.ConfigOverride,
		arg.RegisteredBy,
	)
	return err
}

const deactivateVerticalDefinition = `-- name: DeactivateVerticalDefinition :exec
UPDATE vertical_definitions SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeactivateVerticalDefinition(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateVerticalDefinition, id)
	return err
}

const getTenantVertical = `-- name: GetTenantVertical :one
SELECT tenant_id, vertical_id, config_override, registered_at, registered_by FROM tenant_verticals WHERE tenant_id = $1
`

func (q *Queries) GetTenantVertical(ctx context.Context, tenantID uuid.UUID) (TenantVertical, error) {
	row := q.db.QueryRow(ctx, getTenantVertical, tenantID)
	var i TenantVertical
	err := row.Scan(
		&i.TenantID,
		&i.VerticalID,
		&i.ConfigOverride,
		&i.RegisteredAt,
		&i.RegisteredBy,
	)
	return i, err
}

const getVerticalConfigAndOverride = `-- name: GetVerticalConfigAndOverride :one
SELECT
    vd.config AS base_config,
    tv.config_override AS config_override
FROM tenant_verticals tv
JOIN vertical_definitions vd ON vd.id = tv.vertical_id
WHERE tv.tenant_id = $1
  AND vd.is_active = true
`

type GetVerticalConfigAndOverrideRow struct {
	BaseConfig     json.RawMessage `json:"base_config"`
	ConfigOverride []byte          `json:"config_override"`
}

// Returns base config and override separately for Go-side deep-merge.
func (q *Queries) GetVerticalConfigAndOverride(ctx context.Context, tenantID uuid.UUID) (GetVerticalConfigAndOverrideRow, error) {
	row := q.db.QueryRow(ctx, getVerticalConfigAndOverride, tenantID)
	var i GetVerticalConfigAndOverrideRow
	err := row.Scan(&i.BaseConfig, &i.ConfigOverride)
	return i, err
}

const getVerticalConfigForTenant = `-- name: GetVerticalConfigForTenant :one
SELECT
    vd.config || COALESCE(tv.config_override, '{}'::jsonb) AS merged_config
FROM tenant_verticals tv
JOIN vertical_definitions vd ON vd.id = tv.vertical_id
WHERE tv.tenant_id = $1
  AND vd.is_active = true
`

// Returns the base vertical config merged with any tenant-specific overrides.
// Uses PostgreSQL shallow merge for backward compatibility.
func (q *Queries) GetVerticalConfigForTenant(ctx context.Context, tenantID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getVerticalConfigForTenant, tenantID)
	var merged_config interface{}
	err := row.Scan(&merged_config)
	return merged_config, err
}

const getVerticalDefinition = `-- name: GetVerticalDefinition :one
SELECT id, name, version, description, config, is_active, created_at, updated_at FROM vertical_definitions WHERE id = $1 AND is_active = true
`

func (q *Queries) GetVerticalDefinition(ctx context.Context, id string) (VerticalDefinition, error) {
	row := q.db.QueryRow(ctx, getVerticalDefinition, id)
	var i VerticalDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVerticalDefinitions = `-- name: ListVerticalDefinitions :many
SELECT id, name, version, description
FROM vertical_definitions
WHERE is_active = true
ORDER BY name
`

type ListVerticalDefinitionsRow struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Version     string      `json:"version"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) ListVerticalDefinitions(ctx context.Context) ([]ListVerticalDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listVerticalDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerticalDefinitionsRow{}
	for rows.Next() {
		var i ListVerticalDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbindTenantVertical = `-- name: UnbindTenantVertical :exec
DELETE FROM tenant_verticals WHERE tenant_id = $1
`

func (q *Queries) UnbindTenantVertical(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unbindTenantVertical, tenantID)
	return err
}

const updateTenantVerticalOverride = `-- name: UpdateTenantVerticalOverride :exec
UPDATE tenant_verticals
SET config_override = $2
WHERE tenant_id = $1
`

type UpdateTenantVerticalOverrideParams struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	ConfigOverride []byte    `json:"config_override"`
}

func (q *Queries) UpdateTenantVerticalOverride(ctx context.Context, arg UpdateTenantVerticalOverrideParams) error {
	_, err := q.db.Exec(ctx, updateTenantVerticalOverride, arg.TenantID, arg.ConfigOverride)
	return err
}

const upsertVerticalDefinition = `-- name: UpsertVerticalDefinition :one
INSERT INTO vertical_definitions (id, name, version, description, config)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET name        = EXCLUDED.name,
        version     = EXCLUDED.version,
        description = EXCLUDED.description,
        config      = EXCLUDED.config,
        updated_at  = now()
RETURNING id, name, version, description, config, is_active, created_at, updated_at
`

type UpsertVerticalDefinitionParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Version     string          `json:"version"`
	Description pgtype.Text     `json:"description"`
	Config      json.RawMessage `json:"config"`
}

func (q *Queries) UpsertVerticalDefinition(ctx context.Context, arg UpsertVerticalDefinitionParams) (VerticalDefinition, error) {
	row := q.db.QueryRow(ctx, upsertVerticalDefinition,
		arg.ID,
		arg.Name,
		arg.Version,
		arg.Description,
		arg.Config,
	)
	var i VerticalDefinition
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Version,
		&i.Description,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
