// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getVerticalConfigForTenant = `-- name: GetVerticalConfigForTenant :one
SELECT
    vd.config || COALESCE(tv.config_override, '{}'::jsonb) AS merged_config
FROM tenant_verticals tv
JOIN vertical_definitions vd ON vd.id = tv.vertical_id
WHERE tv.tenant_id = $1
  AND vd.is_active = true
`

func (q *Queries) GetVerticalConfigForTenant(ctx context.Context, tenantID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getVerticalConfigForTenant, tenantID)
	var mergedConfig json.RawMessage
	err := row.Scan(&mergedConfig)
	return mergedConfig, err
}

const getVerticalConfigAndOverride = `-- name: GetVerticalConfigAndOverride :one
SELECT
    vd.config AS base_config,
    tv.config_override AS config_override
FROM tenant_verticals tv
JOIN vertical_definitions vd ON vd.id = tv.vertical_id
WHERE tv.tenant_id = $1
  AND vd.is_active = true
`

// ConfigAndOverride holds the base config and optional override separately.
type ConfigAndOverride struct {
	BaseConfig     json.RawMessage
	ConfigOverride json.RawMessage // may be nil
}

func (q *Queries) GetVerticalConfigAndOverride(ctx context.Context, tenantID uuid.UUID) (ConfigAndOverride, error) {
	row := q.db.QueryRowContext(ctx, getVerticalConfigAndOverride, tenantID)
	var result ConfigAndOverride
	err := row.Scan(&result.BaseConfig, &result.ConfigOverride)
	return result, err
}

const getVerticalDefinition = `-- name: GetVerticalDefinition :one
SELECT id, name, version, description, config, is_active, created_at, updated_at
FROM vertical_definitions WHERE id = $1 AND is_active = true
`

func (q *Queries) GetVerticalDefinition(ctx context.Context, id string) (VerticalDefinition, error) {
	row := q.db.QueryRowContext(ctx, getVerticalDefinition, id)
	var i VerticalDefinition
	err := row.Scan(
		&i.ID, &i.Name, &i.Version, &i.Description,
		&i.Config, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const listVerticalDefinitions = `-- name: ListVerticalDefinitions :many
SELECT id, name, version, description
FROM vertical_definitions
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListVerticalDefinitions(ctx context.Context) ([]ListVerticalDefinitionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listVerticalDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVerticalDefinitionsRow{}
	for rows.Next() {
		var i ListVerticalDefinitionsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Version, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertVerticalDefinition = `-- name: UpsertVerticalDefinition :one
INSERT INTO vertical_definitions (id, name, version, description, config)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE
    SET name        = EXCLUDED.name,
        version     = EXCLUDED.version,
        description = EXCLUDED.description,
        config      = EXCLUDED.config,
        updated_at  = now()
RETURNING id, name, version, description, config, is_active, created_at, updated_at
`

func (q *Queries) UpsertVerticalDefinition(ctx context.Context, arg UpsertVerticalDefinitionParams) (VerticalDefinition, error) {
	row := q.db.QueryRowContext(ctx, upsertVerticalDefinition,
		arg.ID, arg.Name, arg.Version, arg.Description, arg.Config,
	)
	var i VerticalDefinition
	err := row.Scan(
		&i.ID, &i.Name, &i.Version, &i.Description,
		&i.Config, &i.IsActive, &i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deactivateVerticalDefinition = `-- name: DeactivateVerticalDefinition :exec
UPDATE vertical_definitions SET is_active = false, updated_at = now() WHERE id = $1
`

func (q *Queries) DeactivateVerticalDefinition(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deactivateVerticalDefinition, id)
	return err
}

const bindTenantVertical = `-- name: BindTenantVertical :exec
INSERT INTO tenant_verticals (tenant_id, vertical_id, config_override, registered_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id) DO NOTHING
`

func (q *Queries) BindTenantVertical(ctx context.Context, arg BindTenantVerticalParams) error {
	_, err := q.db.ExecContext(ctx, bindTenantVertical,
		arg.TenantID, arg.VerticalID, arg.ConfigOverride, arg.RegisteredBy,
	)
	return err
}

const updateTenantVerticalOverride = `-- name: UpdateTenantVerticalOverride :exec
UPDATE tenant_verticals
SET config_override = $2
WHERE tenant_id = $1
`

func (q *Queries) UpdateTenantVerticalOverride(ctx context.Context, arg UpdateTenantVerticalOverrideParams) error {
	_, err := q.db.ExecContext(ctx, updateTenantVerticalOverride, arg.TenantID, arg.ConfigOverride)
	return err
}

const getTenantVertical = `-- name: GetTenantVertical :one
SELECT tenant_id, vertical_id, config_override, registered_at, registered_by
FROM tenant_verticals WHERE tenant_id = $1
`

func (q *Queries) GetTenantVertical(ctx context.Context, tenantID uuid.UUID) (TenantVertical, error) {
	row := q.db.QueryRowContext(ctx, getTenantVertical, tenantID)
	var i TenantVertical
	err := row.Scan(
		&i.TenantID, &i.VerticalID, &i.ConfigOverride,
		&i.RegisteredAt, &i.RegisteredBy,
	)
	return i, err
}

const unbindTenantVertical = `-- name: UnbindTenantVertical :exec
DELETE FROM tenant_verticals WHERE tenant_id = $1
`

func (q *Queries) UnbindTenantVertical(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, unbindTenantVertical, tenantID)
	return err
}
