// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

// Querier defines all available query methods.
type Querier interface {
	GetVerticalConfigForTenant(ctx context.Context, tenantID uuid.UUID) (json.RawMessage, error)
	GetVerticalDefinition(ctx context.Context, id string) (VerticalDefinition, error)
	ListVerticalDefinitions(ctx context.Context) ([]ListVerticalDefinitionsRow, error)
	UpsertVerticalDefinition(ctx context.Context, arg UpsertVerticalDefinitionParams) (VerticalDefinition, error)
	DeactivateVerticalDefinition(ctx context.Context, id string) error
	BindTenantVertical(ctx context.Context, arg BindTenantVerticalParams) error
	UpdateTenantVerticalOverride(ctx context.Context, arg UpdateTenantVerticalOverrideParams) error
	GetTenantVertical(ctx context.Context, tenantID uuid.UUID) (TenantVertical, error)
	UnbindTenantVertical(ctx context.Context, tenantID uuid.UUID) error
}

type ListVerticalDefinitionsRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Version     string  `json:"version"`
	Description *string `json:"description"`
}

type UpsertVerticalDefinitionParams struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Version     string          `json:"version"`
	Description *string         `json:"description"`
	Config      json.RawMessage `json:"config"`
}

type BindTenantVerticalParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	VerticalID     string          `json:"vertical_id"`
	ConfigOverride json.RawMessage `json:"config_override"`
	RegisteredBy   uuid.UUID       `json:"registered_by"`
}

type UpdateTenantVerticalOverrideParams struct {
	TenantID       uuid.UUID       `json:"tenant_id"`
	ConfigOverride json.RawMessage `json:"config_override"`
}

var _ Querier = (*Queries)(nil)
