// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID           uuid.UUID          `json:"id"`
	ProductionID uuid.UUID          `json:"production_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Label        string             `json:"label"`
	Status       string             `json:"status"`
	Currency     string             `json:"currency"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	SubmittedBy  pgtype.UUID        `json:"submitted_by"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type BudgetLineItem struct {
	ID              uuid.UUID      `json:"id"`
	BudgetID        uuid.UUID      `json:"budget_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	CategoryID      string         `json:"category_id"`
	Description     string         `json:"description"`
	AccountCode     string         `json:"account_code"`
	BudgetedAmount  pgtype.Numeric `json:"budgeted_amount"`
	ActualAmount    pgtype.Numeric `json:"actual_amount"`
	CommittedAmount pgtype.Numeric `json:"committed_amount"`
	IsLocked        bool           `json:"is_locked"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
