// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one

INSERT INTO budgets (id, production_id, tenant_id, label, status, currency, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, production_id, tenant_id, label, status, currency, total_amount, submitted_by, approved_by, submitted_at, approved_at, created_by, created_at, updated_at
`

type CreateBudgetParams struct {
	ID           uuid.UUID `json:"id"`
	ProductionID uuid.UUID `json:"production_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Label        string    `json:"label"`
	Status       string    `json:"status"`
	Currency     string    `json:"currency"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

// Budget planning service queries.
func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.ID,
		arg.ProductionID,
		arg.TenantID,
		arg.Label,
		arg.Status,
		arg.Currency,
		arg.CreatedBy,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.Label,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO budget_line_items (id, budget_id, tenant_id, category_id, description, account_code, budgeted_amount)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, budget_id, tenant_id, category_id, description, account_code, budgeted_amount, actual_amount, committed_amount, is_locked, created_at, updated_at
`

type CreateLineItemParams struct {
	ID             uuid.UUID      `json:"id"`
	BudgetID       uuid.UUID      `json:"budget_id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	CategoryID     string         `json:"category_id"`
	Description    string         `json:"description"`
	AccountCode    string         `json:"account_code"`
	BudgetedAmount pgtype.Numeric `json:"budgeted_amount"`
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (BudgetLineItem, error) {
	row := q.db.QueryRow(ctx, createLineItem,
		arg.ID,
		arg.BudgetID,
		arg.TenantID,
		arg.CategoryID,
		arg.Description,
		arg.AccountCode,
		arg.BudgetedAmount,
	)
	var i BudgetLineItem
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.TenantID,
		&i.CategoryID,
		&i.Description,
		&i.AccountCode,
		&i.BudgetedAmount,
		&i.ActualAmount,
		&i.CommittedAmount,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudget = `-- name: GetBudget :one
SELECT id, production_id, tenant_id, label, status, currency, total_amount, submitted_by, approved_by, submitted_at, approved_at, created_by, created_at, updated_at FROM budgets WHERE id = $1 AND tenant_id = $2
`

type GetBudgetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetBudget(ctx context.Context, arg GetBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudget, arg.ID, arg.TenantID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.Label,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLineItem = `-- name: GetLineItem :one
SELECT id, budget_id, tenant_id, category_id, description, account_code, budgeted_amount, actual_amount, committed_amount, is_locked, created_at, updated_at FROM budget_line_items WHERE id = $1
`

func (q *Queries) GetLineItem(ctx context.Context, id uuid.UUID) (BudgetLineItem, error) {
	row := q.db.QueryRow(ctx, getLineItem, id)
	var i BudgetLineItem
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.TenantID,
		&i.CategoryID,
		&i.Description,
		&i.AccountCode,
		&i.BudgetedAmount,
		&i.ActualAmount,
		&i.CommittedAmount,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgets = `-- name: ListBudgets :many
SELECT id, production_id, tenant_id, label, status, currency, total_amount, submitted_by, approved_by, submitted_at, approved_at, created_by, created_at, updated_at FROM budgets
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR production_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListBudgetsParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgets,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Budget{}
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.TenantID,
			&i.Label,
			&i.Status,
			&i.Currency,
			&i.TotalAmount,
			&i.SubmittedBy,
			&i.ApprovedBy,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLineItems = `-- name: ListLineItems :many
SELECT id, budget_id, tenant_id, category_id, description, account_code, budgeted_amount, actual_amount, committed_amount, is_locked, created_at, updated_at FROM budget_line_items WHERE budget_id = $1 ORDER BY category_id, created_at ASC
`

func (q *Queries) ListLineItems(ctx context.Context, budgetID uuid.UUID) ([]BudgetLineItem, error) {
	rows, err := q.db.Query(ctx, listLineItems, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BudgetLineItem{}
	for rows.Next() {
		var i BudgetLineItem
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.TenantID,
			&i.CategoryID,
			&i.Description,
			&i.AccountCode,
			&i.BudgetedAmount,
			&i.ActualAmount,
			&i.CommittedAmount,
			&i.IsLocked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLineItem = `-- name: LockLineItem :exec
UPDATE budget_line_items SET is_locked = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) LockLineItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockLineItem, id)
	return err
}

const updateBudgetStatus = `-- name: UpdateBudgetStatus :one
UPDATE budgets
SET status       = $3,
    submitted_by = CASE WHEN $3 = 'submitted' THEN $4 ELSE submitted_by END,
    approved_by  = CASE WHEN $3 = 'approved'  THEN $4 ELSE approved_by  END,
    submitted_at = CASE WHEN $3 = 'submitted' THEN now() ELSE submitted_at END,
    approved_at  = CASE WHEN $3 = 'approved'  THEN now() ELSE approved_at  END,
    updated_at   = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, production_id, tenant_id, label, status, currency, total_amount, submitted_by, approved_by, submitted_at, approved_at, created_by, created_at, updated_at
`

type UpdateBudgetStatusParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Status      string      `json:"status"`
	SubmittedBy pgtype.UUID `json:"submitted_by"`
}

func (q *Queries) UpdateBudgetStatus(ctx context.Context, arg UpdateBudgetStatusParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudgetStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.SubmittedBy,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.Label,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudgetTotals = `-- name: UpdateBudgetTotals :exec
UPDATE budgets
SET total_amount = (SELECT COALESCE(SUM(budgeted_amount), 0) FROM budget_line_items WHERE budget_id = $1),
    updated_at  = now()
WHERE id = $1
`

func (q *Queries) UpdateBudgetTotals(ctx context.Context, budgetID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateBudgetTotals, budgetID)
	return err
}

const updateLineItemAmounts = `-- name: UpdateLineItemAmounts :one
UPDATE budget_line_items
SET budgeted_amount  = COALESCE($3, budgeted_amount),
    actual_amount    = COALESCE($4, actual_amount),
    committed_amount = COALESCE($5, committed_amount),
    updated_at       = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, budget_id, tenant_id, category_id, description, account_code, budgeted_amount, actual_amount, committed_amount, is_locked, created_at, updated_at
`

type UpdateLineItemAmountsParams struct {
	ID              uuid.UUID      `json:"id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	BudgetedAmount  pgtype.Numeric `json:"budgeted_amount"`
	ActualAmount    pgtype.Numeric `json:"actual_amount"`
	CommittedAmount pgtype.Numeric `json:"committed_amount"`
}

func (q *Queries) UpdateLineItemAmounts(ctx context.Context, arg UpdateLineItemAmountsParams) (BudgetLineItem, error) {
	row := q.db.QueryRow(ctx, updateLineItemAmounts,
		arg.ID,
		arg.TenantID,
		arg.BudgetedAmount,
		arg.ActualAmount,
		arg.CommittedAmount,
	)
	var i BudgetLineItem
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.TenantID,
		&i.CategoryID,
		&i.Description,
		&i.AccountCode,
		&i.BudgetedAmount,
		&i.ActualAmount,
		&i.CommittedAmount,
		&i.IsLocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
