// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Budget struct {
	ID           uuid.UUID          `json:"id"`
	ProductionID uuid.UUID          `json:"production_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	Label        string             `json:"label"`
	Status       string             `json:"status"`
	Currency     string             `json:"currency"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	SubmittedBy  pgtype.UUID        `json:"submitted_by"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	SubmittedAt  pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type BudgetFact struct {
	BudgetID       uuid.UUID      `json:"budget_id"`
	ProductionID   uuid.UUID      `json:"production_id"`
	TenantID       uuid.UUID      `json:"tenant_id"`
	TotalBudgeted  pgtype.Numeric `json:"total_budgeted"`
	TotalActual    pgtype.Numeric `json:"total_actual"`
	TotalCommitted pgtype.Numeric `json:"total_committed"`
}

type BudgetLineItem struct {
	ID              uuid.UUID      `json:"id"`
	BudgetID        uuid.UUID      `json:"budget_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	CategoryID      string         `json:"category_id"`
	Description     string         `json:"description"`
	AccountCode     string         `json:"account_code"`
	BudgetedAmount  pgtype.Numeric `json:"budgeted_amount"`
	ActualAmount    pgtype.Numeric `json:"actual_amount"`
	CommittedAmount pgtype.Numeric `json:"committed_amount"`
	IsLocked        bool           `json:"is_locked"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type CategorySpend struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	CategoryID   string         `json:"category_id"`
	CategoryName string         `json:"category_name"`
	Budgeted     pgtype.Numeric `json:"budgeted"`
	Actual       pgtype.Numeric `json:"actual"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type ComplianceFlag struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	FlagType     string      `json:"flag_type"`
	Description  string      `json:"description"`
	Severity     string      `json:"severity"`
	ProjectTitle pgtype.Text `json:"project_title"`
	DetectedAt   time.Time   `json:"detected_at"`
}

type CrewMember struct {
	ID           uuid.UUID      `json:"id"`
	ProductionID uuid.UUID      `json:"production_id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	UserID       pgtype.UUID    `json:"user_id"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Department   pgtype.Text    `json:"department"`
	DayRate      pgtype.Numeric `json:"day_rate"`
	Currency     pgtype.Text    `json:"currency"`
	StartDate    pgtype.Date    `json:"start_date"`
	EndDate      pgtype.Date    `json:"end_date"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Expense struct {
	ID              uuid.UUID          `json:"id"`
	ProductionID    uuid.UUID          `json:"production_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	BudgetLineID    pgtype.UUID        `json:"budget_line_id"`
	PurchaseOrderID pgtype.UUID        `json:"purchase_order_id"`
	CategoryID      string             `json:"category_id"`
	Description     pgtype.Text        `json:"description"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	TaxAmount       pgtype.Numeric     `json:"tax_amount"`
	Status          string             `json:"status"`
	SubmittedBy     uuid.UUID          `json:"submitted_by"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	CreatedAt       time.Time          `json:"created_at"`
}

type ExpenseFact struct {
	ExpenseID    uuid.UUID          `json:"expense_id"`
	ProductionID uuid.UUID          `json:"production_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	BudgetLineID pgtype.UUID        `json:"budget_line_id"`
	CategoryID   string             `json:"category_id"`
	Amount       pgtype.Numeric     `json:"amount"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
}

type MonthlySpend struct {
	TenantID  uuid.UUID      `json:"tenant_id"`
	Month     string         `json:"month"`
	Actual    pgtype.Numeric `json:"actual"`
	Budget    pgtype.Numeric `json:"budget"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type PendingApproval struct {
	ID           uuid.UUID      `json:"id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	ItemType     string         `json:"item_type"`
	Description  string         `json:"description"`
	Amount       pgtype.Numeric `json:"amount"`
	SubmittedBy  string         `json:"submitted_by"`
	SubmittedAt  time.Time      `json:"submitted_at"`
	ProjectTitle pgtype.Text    `json:"project_title"`
}

type PettyCashAdvance struct {
	ID            uuid.UUID          `json:"id"`
	ProductionID  uuid.UUID          `json:"production_id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	IssuedTo      uuid.UUID          `json:"issued_to"`
	Amount        pgtype.Numeric     `json:"amount"`
	Purpose       string             `json:"purpose"`
	Status        string             `json:"status"`
	IssuedAt      time.Time          `json:"issued_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
	UnspentAmount pgtype.Numeric     `json:"unspent_amount"`
}

type Phase struct {
	ID           uuid.UUID   `json:"id"`
	ProductionID uuid.UUID   `json:"production_id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	PhaseType    string      `json:"phase_type"`
	Status       string      `json:"status"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type PortfolioSnapshot struct {
	TenantID     uuid.UUID      `json:"tenant_id"`
	ProjectID    uuid.UUID      `json:"project_id"`
	Title        string         `json:"title"`
	Status       string         `json:"status"`
	CurrentPhase pgtype.Text    `json:"current_phase"`
	BudgetTotal  pgtype.Numeric `json:"budget_total"`
	ActualSpend  pgtype.Numeric `json:"actual_spend"`
	Committed    pgtype.Numeric `json:"committed"`
	StartDate    pgtype.Date    `json:"start_date"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Production struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Genre       pgtype.Text `json:"genre"`
	Language    pgtype.Text `json:"language"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}

type ProjectionWatermark struct {
	Subject     string    `json:"subject"`
	LastEventAt time.Time `json:"last_event_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PurchaseOrder struct {
	ID           uuid.UUID          `json:"id"`
	ProductionID uuid.UUID          `json:"production_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	BudgetLineID pgtype.UUID        `json:"budget_line_id"`
	PoNumber     string             `json:"po_number"`
	VendorName   string             `json:"vendor_name"`
	VendorGstin  pgtype.Text        `json:"vendor_gstin"`
	Description  pgtype.Text        `json:"description"`
	Amount       pgtype.Numeric     `json:"amount"`
	Currency     string             `json:"currency"`
	Status       string             `json:"status"`
	RaisedBy     uuid.UUID          `json:"raised_by"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	RaisedAt     time.Time          `json:"raised_at"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type RegistrationSaga struct {
	ID                 uuid.UUID   `json:"id"`
	Email              string      `json:"email"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	UserID             pgtype.UUID `json:"user_id"`
	Status             string      `json:"status"`
	CompletedSteps     []byte      `json:"completed_steps"`
	FailedStep         pgtype.Text `json:"failed_step"`
	FailureReason      pgtype.Text `json:"failure_reason"`
	CompensationErrors []byte      `json:"compensation_errors"`
	Request            []byte      `json:"request"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type TeamAssignment struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	ProjectID    uuid.UUID `json:"project_id"`
	ProjectTitle string    `json:"project_title"`
	MemberCount  int32     `json:"member_count"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type TenantVertical struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	VerticalID     string    `json:"vertical_id"`
	ConfigOverride []byte    `json:"config_override"`
	RegisteredAt   time.Time `json:"registered_at"`
	RegisteredBy   uuid.UUID `json:"registered_by"`
}

type VerticalDefinition struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Version     string      `json:"version"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
