// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBudgetSummary = `-- name: GetBudgetSummary :one

SELECT
    b.id,
    b.label,
    b.status,
    b.total_amount,
    COALESCE(SUM(li.actual_amount),    0) AS actual_spend,
    COALESCE(SUM(li.committed_amount), 0) AS committed_spend
FROM budgets b
LEFT JOIN budget_line_items li ON li.budget_id = b.id
WHERE b.id = $1 AND b.tenant_id = $2
GROUP BY b.id, b.label, b.status, b.total_amount
`

type GetBudgetSummaryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetBudgetSummaryRow struct {
	ID             uuid.UUID      `json:"id"`
	Label          string         `json:"label"`
	Status         string         `json:"status"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	ActualSpend    interface{}    `json:"actual_spend"`
	CommittedSpend interface{}    `json:"committed_spend"`
}

// Reporting analytics service queries.
// Read-only projections. No writes except watermark updates.
func (q *Queries) GetBudgetSummary(ctx context.Context, arg GetBudgetSummaryParams) (GetBudgetSummaryRow, error) {
	row := q.db.QueryRow(ctx, getBudgetSummary, arg.ID, arg.TenantID)
	var i GetBudgetSummaryRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.TotalAmount,
		&i.ActualSpend,
		&i.CommittedSpend,
	)
	return i, err
}

const getExpenseSummaryByCategory = `-- name: GetExpenseSummaryByCategory :many
SELECT
    category_id,
    status,
    COUNT(*)                AS count,
    COALESCE(SUM(amount),0) AS total_amount
FROM expenses
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR production_id = $2)
GROUP BY category_id, status
ORDER BY total_amount DESC
`

type GetExpenseSummaryByCategoryParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
}

type GetExpenseSummaryByCategoryRow struct {
	CategoryID  string      `json:"category_id"`
	Status      string      `json:"status"`
	Count       int64       `json:"count"`
	TotalAmount interface{} `json:"total_amount"`
}

func (q *Queries) GetExpenseSummaryByCategory(ctx context.Context, arg GetExpenseSummaryByCategoryParams) ([]GetExpenseSummaryByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getExpenseSummaryByCategory, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetExpenseSummaryByCategoryRow{}
	for rows.Next() {
		var i GetExpenseSummaryByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.Status,
			&i.Count,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductionFinancialSummary = `-- name: GetProductionFinancialSummary :one
SELECT
    p.id AS production_id,
    p.title,
    COALESCE(b.total_amount, 0)                                    AS budget_total,
    COALESCE(SUM(CASE WHEN e.status='paid' THEN e.amount ELSE 0 END), 0) AS actual_spend,
    COALESCE(SUM(CASE WHEN e.status IN ('submitted','approved') THEN e.amount ELSE 0 END), 0) AS committed_spend
FROM productions p
LEFT JOIN budgets b     ON b.production_id = p.id AND b.status = 'approved'
LEFT JOIN expenses e    ON e.production_id = p.id
WHERE p.id = $1 AND p.tenant_id = $2
GROUP BY p.id, p.title, b.total_amount
`

type GetProductionFinancialSummaryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetProductionFinancialSummaryRow struct {
	ProductionID   uuid.UUID      `json:"production_id"`
	Title          string         `json:"title"`
	BudgetTotal    pgtype.Numeric `json:"budget_total"`
	ActualSpend    interface{}    `json:"actual_spend"`
	CommittedSpend interface{}    `json:"committed_spend"`
}

func (q *Queries) GetProductionFinancialSummary(ctx context.Context, arg GetProductionFinancialSummaryParams) (GetProductionFinancialSummaryRow, error) {
	row := q.db.QueryRow(ctx, getProductionFinancialSummary, arg.ID, arg.TenantID)
	var i GetProductionFinancialSummaryRow
	err := row.Scan(
		&i.ProductionID,
		&i.Title,
		&i.BudgetTotal,
		&i.ActualSpend,
		&i.CommittedSpend,
	)
	return i, err
}

const getProjectionWatermark = `-- name: GetProjectionWatermark :one
SELECT subject, last_event_at, updated_at FROM projection_watermarks WHERE subject = $1
`

func (q *Queries) GetProjectionWatermark(ctx context.Context, subject string) (ProjectionWatermark, error) {
	row := q.db.QueryRow(ctx, getProjectionWatermark, subject)
	var i ProjectionWatermark
	err := row.Scan(&i.Subject, &i.LastEventAt, &i.UpdatedAt)
	return i, err
}

const getTenantDashboardStats = `-- name: GetTenantDashboardStats :one
SELECT
    COUNT(DISTINCT p.id)                             AS production_count,
    COUNT(DISTINCT e.id) FILTER (WHERE e.status = 'submitted') AS pending_approvals,
    COALESCE(SUM(e.amount) FILTER (WHERE e.status = 'paid'), 0) AS total_spent
FROM productions p
LEFT JOIN expenses e ON e.tenant_id = p.tenant_id
WHERE p.tenant_id = $1
`

type GetTenantDashboardStatsRow struct {
	ProductionCount  int64       `json:"production_count"`
	PendingApprovals int64       `json:"pending_approvals"`
	TotalSpent       interface{} `json:"total_spent"`
}

func (q *Queries) GetTenantDashboardStats(ctx context.Context, tenantID uuid.UUID) (GetTenantDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getTenantDashboardStats, tenantID)
	var i GetTenantDashboardStatsRow
	err := row.Scan(&i.ProductionCount, &i.PendingApprovals, &i.TotalSpent)
	return i, err
}

const upsertProjectionWatermark = `-- name: UpsertProjectionWatermark :exec
INSERT INTO projection_watermarks (subject, last_event_at)
VALUES ($1, $2)
ON CONFLICT (subject) DO UPDATE
    SET last_event_at = EXCLUDED.last_event_at,
        updated_at    = now()
`

type UpsertProjectionWatermarkParams struct {
	Subject     string    `json:"subject"`
	LastEventAt time.Time `json:"last_event_at"`
}

func (q *Queries) UpsertProjectionWatermark(ctx context.Context, arg UpsertProjectionWatermarkParams) error {
	_, err := q.db.Exec(ctx, upsertProjectionWatermark, arg.Subject, arg.LastEventAt)
	return err
}
