// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	AssetCode     string         `json:"asset_code"`
	Name          string         `json:"name"`
	CategoryID    string         `json:"category_id"`
	Description   pgtype.Text    `json:"description"`
	OwnershipType string         `json:"ownership_type"`
	Status        string         `json:"status"`
	PurchaseDate  pgtype.Date    `json:"purchase_date"`
	PurchaseCost  pgtype.Numeric `json:"purchase_cost"`
	SerialNumber  pgtype.Text    `json:"serial_number"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

type AssetCheckout struct {
	ID                uuid.UUID          `json:"id"`
	AssetID           uuid.UUID          `json:"asset_id"`
	ProductionID      uuid.UUID          `json:"production_id"`
	TenantID          uuid.UUID          `json:"tenant_id"`
	CheckedOutTo      uuid.UUID          `json:"checked_out_to"`
	CheckedOutAt      time.Time          `json:"checked_out_at"`
	ExpectedReturn    pgtype.Date        `json:"expected_return"`
	CheckedInAt       pgtype.Timestamptz `json:"checked_in_at"`
	ConditionOut      pgtype.Text        `json:"condition_out"`
	ConditionIn       pgtype.Text        `json:"condition_in"`
	Notes             pgtype.Text        `json:"notes"`
	ReportDamage      bool               `json:"report_damage"`
	DamageSeverity    pgtype.Text        `json:"damage_severity"`
	DamageDescription pgtype.Text        `json:"damage_description"`
	RepairCost        pgtype.Numeric     `json:"repair_cost"`
}
