// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkinAsset = `-- name: CheckinAsset :one
UPDATE asset_checkouts
SET checked_in_at = now(),
    condition_in = $3,
    notes = $4,
    report_damage = $5,
    damage_severity = $6,
    damage_description = $7,
    repair_cost = $8
WHERE id = $1 AND tenant_id = $2
RETURNING id, asset_id, production_id, tenant_id, checked_out_to, checked_out_at, expected_return, checked_in_at, condition_out, condition_in, notes, report_damage, damage_severity, damage_description, repair_cost
`

type CheckinAssetParams struct {
	ID                uuid.UUID      `json:"id"`
	TenantID          uuid.UUID      `json:"tenant_id"`
	ConditionIn       pgtype.Text    `json:"condition_in"`
	Notes             pgtype.Text    `json:"notes"`
	ReportDamage      bool           `json:"report_damage"`
	DamageSeverity    pgtype.Text    `json:"damage_severity"`
	DamageDescription pgtype.Text    `json:"damage_description"`
	RepairCost        pgtype.Numeric `json:"repair_cost"`
}

func (q *Queries) CheckinAsset(ctx context.Context, arg CheckinAssetParams) (AssetCheckout, error) {
	row := q.db.QueryRow(ctx, checkinAsset,
		arg.ID,
		arg.TenantID,
		arg.ConditionIn,
		arg.Notes,
		arg.ReportDamage,
		arg.DamageSeverity,
		arg.DamageDescription,
		arg.RepairCost,
	)
	var i AssetCheckout
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ProductionID,
		&i.TenantID,
		&i.CheckedOutTo,
		&i.CheckedOutAt,
		&i.ExpectedReturn,
		&i.CheckedInAt,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.ReportDamage,
		&i.DamageSeverity,
		&i.DamageDescription,
		&i.RepairCost,
	)
	return i, err
}

const checkoutAsset = `-- name: CheckoutAsset :one
INSERT INTO asset_checkouts (id, asset_id, production_id, tenant_id, checked_out_to, expected_return, condition_out)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
RETURNING id, asset_id, production_id, tenant_id, checked_out_to, checked_out_at, expected_return, checked_in_at, condition_out, condition_in, notes, report_damage, damage_severity, damage_description, repair_cost
`

type CheckoutAssetParams struct {
	ID             uuid.UUID   `json:"id"`
	AssetID        uuid.UUID   `json:"asset_id"`
	ProductionID   uuid.UUID   `json:"production_id"`
	TenantID       uuid.UUID   `json:"tenant_id"`
	CheckedOutTo   uuid.UUID   `json:"checked_out_to"`
	ExpectedReturn pgtype.Date `json:"expected_return"`
	ConditionOut   pgtype.Text `json:"condition_out"`
}

func (q *Queries) CheckoutAsset(ctx context.Context, arg CheckoutAssetParams) (AssetCheckout, error) {
	row := q.db.QueryRow(ctx, checkoutAsset,
		arg.ID,
		arg.AssetID,
		arg.ProductionID,
		arg.TenantID,
		arg.CheckedOutTo,
		arg.ExpectedReturn,
		arg.ConditionOut,
	)
	var i AssetCheckout
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ProductionID,
		&i.TenantID,
		&i.CheckedOutTo,
		&i.CheckedOutAt,
		&i.ExpectedReturn,
		&i.CheckedInAt,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.ReportDamage,
		&i.DamageSeverity,
		&i.DamageDescription,
		&i.RepairCost,
	)
	return i, err
}

const createAsset = `-- name: CreateAsset :one

INSERT INTO assets (id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
RETURNING id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number, created_at, updated_at
`

type CreateAssetParams struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	AssetCode     string         `json:"asset_code"`
	Name          string         `json:"name"`
	CategoryID    string         `json:"category_id"`
	Description   pgtype.Text    `json:"description"`
	OwnershipType string         `json:"ownership_type"`
	Status        string         `json:"status"`
	PurchaseDate  pgtype.Date    `json:"purchase_date"`
	PurchaseCost  pgtype.Numeric `json:"purchase_cost"`
	SerialNumber  pgtype.Text    `json:"serial_number"`
}

// Inventory management service queries.
func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.TenantID,
		arg.AssetCode,
		arg.Name,
		arg.CategoryID,
		arg.Description,
		arg.OwnershipType,
		arg.Status,
		arg.PurchaseDate,
		arg.PurchaseCost,
		arg.SerialNumber,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetCode,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.OwnershipType,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveCheckout = `-- name: GetActiveCheckout :one
SELECT id, asset_id, production_id, tenant_id, checked_out_to, checked_out_at, expected_return, checked_in_at, condition_out, condition_in, notes, report_damage, damage_severity, damage_description, repair_cost FROM asset_checkouts
WHERE asset_id = $1 AND tenant_id = $2 AND checked_in_at IS NULL
LIMIT 1
`

type GetActiveCheckoutParams struct {
	AssetID  uuid.UUID `json:"asset_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetActiveCheckout(ctx context.Context, arg GetActiveCheckoutParams) (AssetCheckout, error) {
	row := q.db.QueryRow(ctx, getActiveCheckout, arg.AssetID, arg.TenantID)
	var i AssetCheckout
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ProductionID,
		&i.TenantID,
		&i.CheckedOutTo,
		&i.CheckedOutAt,
		&i.ExpectedReturn,
		&i.CheckedInAt,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.ReportDamage,
		&i.DamageSeverity,
		&i.DamageDescription,
		&i.RepairCost,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number, created_at, updated_at FROM assets WHERE id = $1 AND tenant_id = $2
`

type GetAssetParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAsset(ctx context.Context, arg GetAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, arg.ID, arg.TenantID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetCode,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.OwnershipType,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByCode = `-- name: GetAssetByCode :one
SELECT id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number, created_at, updated_at FROM assets WHERE asset_code = $1 AND tenant_id = $2
`

type GetAssetByCodeParams struct {
	AssetCode string    `json:"asset_code"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAssetByCode(ctx context.Context, arg GetAssetByCodeParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByCode, arg.AssetCode, arg.TenantID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetCode,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.OwnershipType,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckout = `-- name: GetCheckout :one
SELECT id, asset_id, production_id, tenant_id, checked_out_to, checked_out_at, expected_return, checked_in_at, condition_out, condition_in, notes, report_damage, damage_severity, damage_description, repair_cost FROM asset_checkouts WHERE id = $1 AND tenant_id = $2
`

type GetCheckoutParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetCheckout(ctx context.Context, arg GetCheckoutParams) (AssetCheckout, error) {
	row := q.db.QueryRow(ctx, getCheckout, arg.ID, arg.TenantID)
	var i AssetCheckout
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.ProductionID,
		&i.TenantID,
		&i.CheckedOutTo,
		&i.CheckedOutAt,
		&i.ExpectedReturn,
		&i.CheckedInAt,
		&i.ConditionOut,
		&i.ConditionIn,
		&i.Notes,
		&i.ReportDamage,
		&i.DamageSeverity,
		&i.DamageDescription,
		&i.RepairCost,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number, created_at, updated_at FROM assets
WHERE tenant_id = $1
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR category_id = $3)
  AND ($6 = '' OR name ILIKE '%' || $6 || '%' OR asset_code ILIKE '%' || $6 || '%')
ORDER BY name ASC
LIMIT $4 OFFSET $5
`

type ListAssetsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Column3  interface{} `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Column6  interface{} `json:"column_6"`
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
		arg.Column6,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.AssetCode,
			&i.Name,
			&i.CategoryID,
			&i.Description,
			&i.OwnershipType,
			&i.Status,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.SerialNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckouts = `-- name: ListCheckouts :many
SELECT id, asset_id, production_id, tenant_id, checked_out_to, checked_out_at, expected_return, checked_in_at, condition_out, condition_in, notes, report_damage, damage_severity, damage_description, repair_cost FROM asset_checkouts
WHERE tenant_id = $1::uuid
  AND ($2::uuid IS NULL OR asset_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR checked_out_at < $3::timestamptz)
ORDER BY checked_out_at DESC
LIMIT $4::int
`

type ListCheckoutsParams struct {
	TenantID uuid.UUID          `json:"tenant_id"`
	AssetID  pgtype.UUID        `json:"asset_id"`
	After    pgtype.Timestamptz `json:"after"`
	Limit    int32              `json:"limit"`
}

func (q *Queries) ListCheckouts(ctx context.Context, arg ListCheckoutsParams) ([]AssetCheckout, error) {
	rows, err := q.db.Query(ctx, listCheckouts,
		arg.TenantID,
		arg.AssetID,
		arg.After,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssetCheckout{}
	for rows.Next() {
		var i AssetCheckout
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.ProductionID,
			&i.TenantID,
			&i.CheckedOutTo,
			&i.CheckedOutAt,
			&i.ExpectedReturn,
			&i.CheckedInAt,
			&i.ConditionOut,
			&i.ConditionIn,
			&i.Notes,
			&i.ReportDamage,
			&i.DamageSeverity,
			&i.DamageDescription,
			&i.RepairCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET name         = COALESCE(NULLIF($3, ''), name),
    description  = $4,
    category_id  = COALESCE(NULLIF($5, ''), category_id),
    updated_at   = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number, created_at, updated_at
`

type UpdateAssetParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Column3     interface{} `json:"column_3"`
	Description pgtype.Text `json:"description"`
	Column5     interface{} `json:"column_5"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.TenantID,
		arg.Column3,
		arg.Description,
		arg.Column5,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetCode,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.OwnershipType,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetStatus = `-- name: UpdateAssetStatus :one
UPDATE assets SET status = $3, updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, asset_code, name, category_id, description, ownership_type, status, purchase_date, purchase_cost, serial_number, created_at, updated_at
`

type UpdateAssetStatusParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateAssetStatus(ctx context.Context, arg UpdateAssetStatusParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAssetStatus, arg.ID, arg.TenantID, arg.Status)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AssetCode,
		&i.Name,
		&i.CategoryID,
		&i.Description,
		&i.OwnershipType,
		&i.Status,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.SerialNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
