// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CrewMember struct {
	ID           uuid.UUID      `json:"id"`
	ProductionID uuid.UUID      `json:"production_id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	UserID       pgtype.UUID    `json:"user_id"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Department   pgtype.Text    `json:"department"`
	DayRate      pgtype.Numeric `json:"day_rate"`
	Currency     pgtype.Text    `json:"currency"`
	StartDate    pgtype.Date    `json:"start_date"`
	EndDate      pgtype.Date    `json:"end_date"`
	CreatedAt    time.Time      `json:"created_at"`
}

type Phase struct {
	ID           uuid.UUID   `json:"id"`
	ProductionID uuid.UUID   `json:"production_id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	PhaseType    string      `json:"phase_type"`
	Status       string      `json:"status"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Production struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Genre       pgtype.Text `json:"genre"`
	Language    pgtype.Text `json:"language"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	CreatedBy   uuid.UUID   `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
