// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCrewMember = `-- name: AddCrewMember :one
INSERT INTO crew_members (id, production_id, tenant_id, user_id, name, role, department, day_rate, currency, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
RETURNING id, production_id, tenant_id, user_id, name, role, department, day_rate, currency, start_date, end_date, created_at
`

type AddCrewMemberParams struct {
	ID           uuid.UUID      `json:"id"`
	ProductionID uuid.UUID      `json:"production_id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	UserID       pgtype.UUID    `json:"user_id"`
	Name         string         `json:"name"`
	Role         string         `json:"role"`
	Department   pgtype.Text    `json:"department"`
	DayRate      pgtype.Numeric `json:"day_rate"`
	Currency     pgtype.Text    `json:"currency"`
	StartDate    pgtype.Date    `json:"start_date"`
	EndDate      pgtype.Date    `json:"end_date"`
}

func (q *Queries) AddCrewMember(ctx context.Context, arg AddCrewMemberParams) (CrewMember, error) {
	row := q.db.QueryRow(ctx, addCrewMember,
		arg.ID,
		arg.ProductionID,
		arg.TenantID,
		arg.UserID,
		arg.Name,
		arg.Role,
		arg.Department,
		arg.DayRate,
		arg.Currency,
		arg.StartDate,
		arg.EndDate,
	)
	var i CrewMember
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.Department,
		&i.DayRate,
		&i.Currency,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
	)
	return i, err
}

const archiveProduction = `-- name: ArchiveProduction :one
UPDATE productions SET status = 'archived', updated_at = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, title, slug, description, genre, language, status, start_date, end_date, created_by, created_at, updated_at
`

type ArchiveProductionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ArchiveProduction(ctx context.Context, arg ArchiveProductionParams) (Production, error) {
	row := q.db.QueryRow(ctx, archiveProduction, arg.ID, arg.TenantID)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Genre,
		&i.Language,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPhase = `-- name: CreatePhase :one
INSERT INTO phases (id, production_id, tenant_id, phase_type, status, start_date, end_date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, production_id, tenant_id, phase_type, status, start_date, end_date, created_at, updated_at
`

type CreatePhaseParams struct {
	ID           uuid.UUID   `json:"id"`
	ProductionID uuid.UUID   `json:"production_id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	PhaseType    string      `json:"phase_type"`
	Status       string      `json:"status"`
	StartDate    pgtype.Date `json:"start_date"`
	EndDate      pgtype.Date `json:"end_date"`
}

func (q *Queries) CreatePhase(ctx context.Context, arg CreatePhaseParams) (Phase, error) {
	row := q.db.QueryRow(ctx, createPhase,
		arg.ID,
		arg.ProductionID,
		arg.TenantID,
		arg.PhaseType,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
	)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.PhaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProduction = `-- name: CreateProduction :one

INSERT INTO productions (id, tenant_id, title, slug, description, genre, language, status, start_date, end_date, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
RETURNING id, tenant_id, title, slug, description, genre, language, status, start_date, end_date, created_by, created_at, updated_at
`

type CreateProductionParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Genre       pgtype.Text `json:"genre"`
	Language    pgtype.Text `json:"language"`
	Status      string      `json:"status"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

// Project management service queries.
// All tables live in the tenant-scoped schema (tenant_<uuid>).
func (q *Queries) CreateProduction(ctx context.Context, arg CreateProductionParams) (Production, error) {
	row := q.db.QueryRow(ctx, createProduction,
		arg.ID,
		arg.TenantID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Genre,
		arg.Language,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedBy,
	)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Genre,
		&i.Language,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhase = `-- name: GetPhase :one
SELECT id, production_id, tenant_id, phase_type, status, start_date, end_date, created_at, updated_at FROM phases WHERE id = $1 AND tenant_id = $2
`

type GetPhaseParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPhase(ctx context.Context, arg GetPhaseParams) (Phase, error) {
	row := q.db.QueryRow(ctx, getPhase, arg.ID, arg.TenantID)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.PhaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduction = `-- name: GetProduction :one
SELECT id, tenant_id, title, slug, description, genre, language, status, start_date, end_date, created_by, created_at, updated_at FROM productions
WHERE id = $1 AND tenant_id = $2
`

type GetProductionParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetProduction(ctx context.Context, arg GetProductionParams) (Production, error) {
	row := q.db.QueryRow(ctx, getProduction, arg.ID, arg.TenantID)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Genre,
		&i.Language,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCrewMembers = `-- name: ListCrewMembers :many
SELECT id, production_id, tenant_id, user_id, name, role, department, day_rate, currency, start_date, end_date, created_at FROM crew_members WHERE production_id = $1 AND tenant_id = $2 ORDER BY name ASC LIMIT $3 OFFSET $4
`

type ListCrewMembersParams struct {
	ProductionID uuid.UUID `json:"production_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListCrewMembers(ctx context.Context, arg ListCrewMembersParams) ([]CrewMember, error) {
	rows, err := q.db.Query(ctx, listCrewMembers,
		arg.ProductionID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrewMember{}
	for rows.Next() {
		var i CrewMember
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.Role,
			&i.Department,
			&i.DayRate,
			&i.Currency,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhases = `-- name: ListPhases :many
SELECT id, production_id, tenant_id, phase_type, status, start_date, end_date, created_at, updated_at FROM phases WHERE production_id = $1 AND tenant_id = $2 ORDER BY created_at ASC LIMIT $3 OFFSET $4
`

type ListPhasesParams struct {
	ProductionID uuid.UUID `json:"production_id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

func (q *Queries) ListPhases(ctx context.Context, arg ListPhasesParams) ([]Phase, error) {
	rows, err := q.db.Query(ctx, listPhases,
		arg.ProductionID,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Phase{}
	for rows.Next() {
		var i Phase
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.TenantID,
			&i.PhaseType,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductions = `-- name: ListProductions :many
SELECT id, tenant_id, title, slug, description, genre, language, status, start_date, end_date, created_by, created_at, updated_at FROM productions
WHERE tenant_id = $1
  AND ($2 = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListProductionsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListProductions(ctx context.Context, arg ListProductionsParams) ([]Production, error) {
	rows, err := q.db.Query(ctx, listProductions,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Production{}
	for rows.Next() {
		var i Production
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Genre,
			&i.Language,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCrewMember = `-- name: RemoveCrewMember :exec
DELETE FROM crew_members WHERE id = $1 AND tenant_id = $2
`

type RemoveCrewMemberParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) RemoveCrewMember(ctx context.Context, arg RemoveCrewMemberParams) error {
	_, err := q.db.Exec(ctx, removeCrewMember, arg.ID, arg.TenantID)
	return err
}

const updatePhaseStatus = `-- name: UpdatePhaseStatus :one
UPDATE phases SET status = $2, updated_at = now()
WHERE id = $1 AND tenant_id = $3
RETURNING id, production_id, tenant_id, phase_type, status, start_date, end_date, created_at, updated_at
`

type UpdatePhaseStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdatePhaseStatus(ctx context.Context, arg UpdatePhaseStatusParams) (Phase, error) {
	row := q.db.QueryRow(ctx, updatePhaseStatus, arg.ID, arg.Status, arg.TenantID)
	var i Phase
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.PhaseType,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduction = `-- name: UpdateProduction :one
UPDATE productions
SET title       = COALESCE(NULLIF($3, ''), title),
    description = $4,
    genre       = COALESCE(NULLIF($5, ''), genre),
    status      = COALESCE(NULLIF($6, ''), status),
    start_date  = $7,
    end_date    = $8,
    updated_at  = now()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, title, slug, description, genre, language, status, start_date, end_date, created_by, created_at, updated_at
`

type UpdateProductionParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Column3     interface{} `json:"column_3"`
	Description pgtype.Text `json:"description"`
	Column5     interface{} `json:"column_5"`
	Column6     interface{} `json:"column_6"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateProduction(ctx context.Context, arg UpdateProductionParams) (Production, error) {
	row := q.db.QueryRow(ctx, updateProduction,
		arg.ID,
		arg.TenantID,
		arg.Column3,
		arg.Description,
		arg.Column5,
		arg.Column6,
		arg.StartDate,
		arg.EndDate,
	)
	var i Production
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Genre,
		&i.Language,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
