-- 009_create_invitations.up.sql
-- Pending user invitations. A secure random token is generated by the IAM
-- service and emailed to the invitee. Tokens expire after 7 days.
-- Accepted invitations are kept for audit purposes (never deleted).

CREATE TABLE invitations (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email       TEXT        NOT NULL,
    role_id     UUID        REFERENCES roles(id) ON DELETE SET NULL,
    token       TEXT        NOT NULL UNIQUE,
    status      TEXT        NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'accepted', 'expired')),
    invited_by  UUID        NOT NULL REFERENCES users(id),
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_invitations_tenant ON invitations (tenant_id);
CREATE INDEX idx_invitations_token  ON invitations (token);
CREATE INDEX idx_invitations_email  ON invitations (tenant_id, email);
