// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (id, tenant_id, production_id, folder_id, name, mime_type, size_bytes, storage_key, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, production_id, folder_id, name, mime_type, size_bytes, storage_key, current_version, uploaded_by, created_at, deleted_at
`

type CreateDocumentParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	ProductionID pgtype.UUID `json:"production_id"`
	FolderID     pgtype.UUID `json:"folder_id"`
	Name         string      `json:"name"`
	MimeType     string      `json:"mime_type"`
	SizeBytes    int64       `json:"size_bytes"`
	StorageKey   string      `json:"storage_key"`
	UploadedBy   uuid.UUID   `json:"uploaded_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.TenantID,
		arg.ProductionID,
		arg.FolderID,
		arg.Name,
		arg.MimeType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.FolderID,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CurrentVersion,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDocumentVersion = `-- name: CreateDocumentVersion :one
INSERT INTO document_versions (id, document_id, version, storage_key, size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, version, storage_key, size_bytes, uploaded_by, created_at
`

type CreateDocumentVersionParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	Version    int32     `json:"version"`
	StorageKey string    `json:"storage_key"`
	SizeBytes  int64     `json:"size_bytes"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateDocumentVersion(ctx context.Context, arg CreateDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, createDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.Version,
		arg.StorageKey,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.StorageKey,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createFolder = `-- name: CreateFolder :one

INSERT INTO folders (id, tenant_id, production_id, name, parent_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, production_id, name, parent_id, created_by, created_at
`

type CreateFolderParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	ProductionID pgtype.UUID `json:"production_id"`
	Name         string      `json:"name"`
	ParentID     pgtype.UUID `json:"parent_id"`
	CreatedBy    uuid.UUID   `json:"created_by"`
}

// Document service queries.
func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, createFolder,
		arg.ID,
		arg.TenantID,
		arg.ProductionID,
		arg.Name,
		arg.ParentID,
		arg.CreatedBy,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.Name,
		&i.ParentID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT id, tenant_id, production_id, folder_id, name, mime_type, size_bytes, storage_key, current_version, uploaded_by, created_at, deleted_at FROM documents WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.TenantID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.FolderID,
		&i.Name,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.CurrentVersion,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, version, storage_key, size_bytes, uploaded_by, created_at FROM document_versions WHERE document_id = $1 AND version = $2
`

type GetDocumentVersionParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Version    int32     `json:"version"`
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (DocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.Version)
	var i DocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Version,
		&i.StorageKey,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getFolder = `-- name: GetFolder :one
SELECT id, tenant_id, production_id, name, parent_id, created_by, created_at FROM folders WHERE id = $1 AND tenant_id = $2
`

type GetFolderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, getFolder, arg.ID, arg.TenantID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.Name,
		&i.ParentID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentVersions = `-- name: ListDocumentVersions :many
SELECT id, document_id, version, storage_key, size_bytes, uploaded_by, created_at FROM document_versions
WHERE document_id = $1
ORDER BY version ASC
LIMIT $2 OFFSET $3
`

type ListDocumentVersionsParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListDocumentVersions(ctx context.Context, arg ListDocumentVersionsParams) ([]DocumentVersion, error) {
	rows, err := q.db.Query(ctx, listDocumentVersions, arg.DocumentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentVersion{}
	for rows.Next() {
		var i DocumentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Version,
			&i.StorageKey,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE documents SET deleted_at = now() WHERE id = $1 AND tenant_id = $2
`

type SoftDeleteDocumentParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) SoftDeleteDocument(ctx context.Context, arg SoftDeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, arg.ID, arg.TenantID)
	return err
}
