// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID              uuid.UUID          `json:"id"`
	ProductionID    uuid.UUID          `json:"production_id"`
	TenantID        uuid.UUID          `json:"tenant_id"`
	BudgetLineID    pgtype.UUID        `json:"budget_line_id"`
	PurchaseOrderID pgtype.UUID        `json:"purchase_order_id"`
	CategoryID      string             `json:"category_id"`
	Description     pgtype.Text        `json:"description"`
	Amount          pgtype.Numeric     `json:"amount"`
	Currency        string             `json:"currency"`
	TaxAmount       pgtype.Numeric     `json:"tax_amount"`
	Status          string             `json:"status"`
	SubmittedBy     uuid.UUID          `json:"submitted_by"`
	ApprovedBy      pgtype.UUID        `json:"approved_by"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	ApprovedAt      pgtype.Timestamptz `json:"approved_at"`
	CreatedAt       time.Time          `json:"created_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	RejectedAt      pgtype.Timestamptz `json:"rejected_at"`
	RejectedBy      pgtype.UUID        `json:"rejected_by"`
}

type PettyCashAdvance struct {
	ID            uuid.UUID          `json:"id"`
	ProductionID  uuid.UUID          `json:"production_id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	IssuedTo      uuid.UUID          `json:"issued_to"`
	Amount        pgtype.Numeric     `json:"amount"`
	Purpose       string             `json:"purpose"`
	Status        string             `json:"status"`
	IssuedAt      time.Time          `json:"issued_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
	UnspentAmount pgtype.Numeric     `json:"unspent_amount"`
}

type PurchaseOrder struct {
	ID           uuid.UUID          `json:"id"`
	ProductionID uuid.UUID          `json:"production_id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	BudgetLineID pgtype.UUID        `json:"budget_line_id"`
	PoNumber     string             `json:"po_number"`
	VendorName   string             `json:"vendor_name"`
	VendorGstin  pgtype.Text        `json:"vendor_gstin"`
	Description  pgtype.Text        `json:"description"`
	Amount       pgtype.Numeric     `json:"amount"`
	Currency     string             `json:"currency"`
	Status       string             `json:"status"`
	RaisedBy     uuid.UUID          `json:"raised_by"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	RaisedAt     time.Time          `json:"raised_at"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	CreatedAt    time.Time          `json:"created_at"`
}
