// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, production_id, tenant_id, budget_line_id, purchase_order_id, category_id, description, amount, currency, tax_amount, submitted_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
RETURNING id, production_id, tenant_id, budget_line_id, purchase_order_id, category_id, description, amount, currency, tax_amount, status, submitted_by, approved_by, submitted_at, approved_at, created_at, rejection_reason, rejected_at, rejected_by
`

type CreateExpenseParams struct {
	ID              uuid.UUID      `json:"id"`
	ProductionID    uuid.UUID      `json:"production_id"`
	TenantID        uuid.UUID      `json:"tenant_id"`
	BudgetLineID    pgtype.UUID    `json:"budget_line_id"`
	PurchaseOrderID pgtype.UUID    `json:"purchase_order_id"`
	CategoryID      string         `json:"category_id"`
	Description     pgtype.Text    `json:"description"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	TaxAmount       pgtype.Numeric `json:"tax_amount"`
	SubmittedBy     uuid.UUID      `json:"submitted_by"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.ProductionID,
		arg.TenantID,
		arg.BudgetLineID,
		arg.PurchaseOrderID,
		arg.CategoryID,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.TaxAmount,
		arg.SubmittedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PurchaseOrderID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.TaxAmount,
		&i.Status,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.RejectionReason,
		&i.RejectedAt,
		&i.RejectedBy,
	)
	return i, err
}

const createPettyCashAdvance = `-- name: CreatePettyCashAdvance :one
INSERT INTO petty_cash_advances (id, production_id, tenant_id, issued_to, amount, purpose)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
RETURNING id, production_id, tenant_id, issued_to, amount, purpose, status, issued_at, settled_at, unspent_amount
`

type CreatePettyCashAdvanceParams struct {
	ID           uuid.UUID      `json:"id"`
	ProductionID uuid.UUID      `json:"production_id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	IssuedTo     uuid.UUID      `json:"issued_to"`
	Amount       pgtype.Numeric `json:"amount"`
	Purpose      string         `json:"purpose"`
}

func (q *Queries) CreatePettyCashAdvance(ctx context.Context, arg CreatePettyCashAdvanceParams) (PettyCashAdvance, error) {
	row := q.db.QueryRow(ctx, createPettyCashAdvance,
		arg.ID,
		arg.ProductionID,
		arg.TenantID,
		arg.IssuedTo,
		arg.Amount,
		arg.Purpose,
	)
	var i PettyCashAdvance
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.IssuedTo,
		&i.Amount,
		&i.Purpose,
		&i.Status,
		&i.IssuedAt,
		&i.SettledAt,
		&i.UnspentAmount,
	)
	return i, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one

INSERT INTO purchase_orders (id, production_id, tenant_id, budget_line_id, po_number, vendor_name, vendor_gstin, description, amount, currency, raised_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
RETURNING id, production_id, tenant_id, budget_line_id, po_number, vendor_name, vendor_gstin, description, amount, currency, status, raised_by, approved_by, raised_at, approved_at, created_at
`

type CreatePurchaseOrderParams struct {
	ID           uuid.UUID      `json:"id"`
	ProductionID uuid.UUID      `json:"production_id"`
	TenantID     uuid.UUID      `json:"tenant_id"`
	BudgetLineID pgtype.UUID    `json:"budget_line_id"`
	PoNumber     string         `json:"po_number"`
	VendorName   string         `json:"vendor_name"`
	VendorGstin  pgtype.Text    `json:"vendor_gstin"`
	Description  pgtype.Text    `json:"description"`
	Amount       pgtype.Numeric `json:"amount"`
	Currency     string         `json:"currency"`
	RaisedBy     uuid.UUID      `json:"raised_by"`
}

// Expense tracking service queries.
func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.ID,
		arg.ProductionID,
		arg.TenantID,
		arg.BudgetLineID,
		arg.PoNumber,
		arg.VendorName,
		arg.VendorGstin,
		arg.Description,
		arg.Amount,
		arg.Currency,
		arg.RaisedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PoNumber,
		&i.VendorName,
		&i.VendorGstin,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.RaisedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExpense = `-- name: GetExpense :one
SELECT id, production_id, tenant_id, budget_line_id, purchase_order_id, category_id, description, amount, currency, tax_amount, status, submitted_by, approved_by, submitted_at, approved_at, created_at, rejection_reason, rejected_at, rejected_by FROM expenses WHERE id = $1 AND tenant_id = $2
`

type GetExpenseParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.TenantID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PurchaseOrderID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.TaxAmount,
		&i.Status,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.RejectionReason,
		&i.RejectedAt,
		&i.RejectedBy,
	)
	return i, err
}

const getPettyCashAdvance = `-- name: GetPettyCashAdvance :one
SELECT id, production_id, tenant_id, issued_to, amount, purpose, status, issued_at, settled_at, unspent_amount FROM petty_cash_advances WHERE id = $1 AND tenant_id = $2
`

type GetPettyCashAdvanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPettyCashAdvance(ctx context.Context, arg GetPettyCashAdvanceParams) (PettyCashAdvance, error) {
	row := q.db.QueryRow(ctx, getPettyCashAdvance, arg.ID, arg.TenantID)
	var i PettyCashAdvance
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.IssuedTo,
		&i.Amount,
		&i.Purpose,
		&i.Status,
		&i.IssuedAt,
		&i.SettledAt,
		&i.UnspentAmount,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, production_id, tenant_id, budget_line_id, po_number, vendor_name, vendor_gstin, description, amount, currency, status, raised_by, approved_by, raised_at, approved_at, created_at FROM purchase_orders WHERE id = $1 AND tenant_id = $2
`

type GetPurchaseOrderParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.ID, arg.TenantID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PoNumber,
		&i.VendorName,
		&i.VendorGstin,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.RaisedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, production_id, tenant_id, budget_line_id, purchase_order_id, category_id, description, amount, currency, tax_amount, status, submitted_by, approved_by, submitted_at, approved_at, created_at, rejection_reason, rejected_at, rejected_by FROM expenses
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR production_id = $2)
  AND ($3 = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListExpensesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  uuid.UUID   `json:"column_2"`
	Column3  interface{} `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Expense{}
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.TenantID,
			&i.BudgetLineID,
			&i.PurchaseOrderID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.TaxAmount,
			&i.Status,
			&i.SubmittedBy,
			&i.ApprovedBy,
			&i.SubmittedAt,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.RejectionReason,
			&i.RejectedAt,
			&i.RejectedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPettyCashAdvances = `-- name: ListPettyCashAdvances :many
SELECT id, production_id, tenant_id, issued_to, amount, purpose, status, issued_at, settled_at, unspent_amount FROM petty_cash_advances
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR production_id = $2)
ORDER BY issued_at DESC
LIMIT $3 OFFSET $4
`

type ListPettyCashAdvancesParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPettyCashAdvances(ctx context.Context, arg ListPettyCashAdvancesParams) ([]PettyCashAdvance, error) {
	rows, err := q.db.Query(ctx, listPettyCashAdvances,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PettyCashAdvance{}
	for rows.Next() {
		var i PettyCashAdvance
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.TenantID,
			&i.IssuedTo,
			&i.Amount,
			&i.Purpose,
			&i.Status,
			&i.IssuedAt,
			&i.SettledAt,
			&i.UnspentAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, production_id, tenant_id, budget_line_id, po_number, vendor_name, vendor_gstin, description, amount, currency, status, raised_by, approved_by, raised_at, approved_at, created_at FROM purchase_orders
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR production_id = $2)
ORDER BY raised_at DESC
LIMIT $3 OFFSET $4
`

type ListPurchaseOrdersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseOrder{}
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.ProductionID,
			&i.TenantID,
			&i.BudgetLineID,
			&i.PoNumber,
			&i.VendorName,
			&i.VendorGstin,
			&i.Description,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.RaisedBy,
			&i.ApprovedBy,
			&i.RaisedAt,
			&i.ApprovedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectExpense = `-- name: RejectExpense :one
UPDATE expenses
SET status = 'rejected', rejection_reason = $3, rejected_at = now(), rejected_by = $4
WHERE id = $1 AND tenant_id = $2
RETURNING id, production_id, tenant_id, budget_line_id, purchase_order_id, category_id, description, amount, currency, tax_amount, status, submitted_by, approved_by, submitted_at, approved_at, created_at, rejection_reason, rejected_at, rejected_by
`

type RejectExpenseParams struct {
	ID              uuid.UUID   `json:"id"`
	TenantID        uuid.UUID   `json:"tenant_id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
	RejectedBy      pgtype.UUID `json:"rejected_by"`
}

func (q *Queries) RejectExpense(ctx context.Context, arg RejectExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, rejectExpense,
		arg.ID,
		arg.TenantID,
		arg.RejectionReason,
		arg.RejectedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PurchaseOrderID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.TaxAmount,
		&i.Status,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.RejectionReason,
		&i.RejectedAt,
		&i.RejectedBy,
	)
	return i, err
}

const settlePettyCashAdvance = `-- name: SettlePettyCashAdvance :one
UPDATE petty_cash_advances
SET status         = $3,
    unspent_amount = $4,
    settled_at     = CASE WHEN $3 = 'settled' THEN now() ELSE settled_at END
WHERE id = $1 AND tenant_id = $2
RETURNING id, production_id, tenant_id, issued_to, amount, purpose, status, issued_at, settled_at, unspent_amount
`

type SettlePettyCashAdvanceParams struct {
	ID            uuid.UUID      `json:"id"`
	TenantID      uuid.UUID      `json:"tenant_id"`
	Status        string         `json:"status"`
	UnspentAmount pgtype.Numeric `json:"unspent_amount"`
}

func (q *Queries) SettlePettyCashAdvance(ctx context.Context, arg SettlePettyCashAdvanceParams) (PettyCashAdvance, error) {
	row := q.db.QueryRow(ctx, settlePettyCashAdvance,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.UnspentAmount,
	)
	var i PettyCashAdvance
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.IssuedTo,
		&i.Amount,
		&i.Purpose,
		&i.Status,
		&i.IssuedAt,
		&i.SettledAt,
		&i.UnspentAmount,
	)
	return i, err
}

const updateExpenseStatus = `-- name: UpdateExpenseStatus :one
UPDATE expenses
SET status      = $3,
    approved_by = CASE WHEN $3 = 'approved' THEN $4 ELSE approved_by END,
    submitted_at = CASE WHEN $3 = 'submitted' THEN now() ELSE submitted_at END,
    approved_at  = CASE WHEN $3 = 'approved'  THEN now() ELSE approved_at  END
WHERE id = $1 AND tenant_id = $2
RETURNING id, production_id, tenant_id, budget_line_id, purchase_order_id, category_id, description, amount, currency, tax_amount, status, submitted_by, approved_by, submitted_at, approved_at, created_at, rejection_reason, rejected_at, rejected_by
`

type UpdateExpenseStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	Status     string      `json:"status"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) UpdateExpenseStatus(ctx context.Context, arg UpdateExpenseStatusParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpenseStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.ApprovedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PurchaseOrderID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.TaxAmount,
		&i.Status,
		&i.SubmittedBy,
		&i.ApprovedBy,
		&i.SubmittedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.RejectionReason,
		&i.RejectedAt,
		&i.RejectedBy,
	)
	return i, err
}

const updatePurchaseOrderStatus = `-- name: UpdatePurchaseOrderStatus :one
UPDATE purchase_orders
SET status      = $3,
    approved_by = CASE WHEN $3 = 'approved' THEN $4 ELSE approved_by END,
    approved_at = CASE WHEN $3 = 'approved' THEN now() ELSE approved_at END
WHERE id = $1 AND tenant_id = $2
RETURNING id, production_id, tenant_id, budget_line_id, po_number, vendor_name, vendor_gstin, description, amount, currency, status, raised_by, approved_by, raised_at, approved_at, created_at
`

type UpdatePurchaseOrderStatusParams struct {
	ID         uuid.UUID   `json:"id"`
	TenantID   uuid.UUID   `json:"tenant_id"`
	Status     string      `json:"status"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderStatus,
		arg.ID,
		arg.TenantID,
		arg.Status,
		arg.ApprovedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.ProductionID,
		&i.TenantID,
		&i.BudgetLineID,
		&i.PoNumber,
		&i.VendorName,
		&i.VendorGstin,
		&i.Description,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RaisedBy,
		&i.ApprovedBy,
		&i.RaisedAt,
		&i.ApprovedAt,
		&i.CreatedAt,
	)
	return i, err
}
