// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :exec
UPDATE invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptInvitation, id)
	return err
}

const approveTenantPurgeRequest = `-- name: ApproveTenantPurgeRequest :one
UPDATE tenant_purge_requests
   SET status = 'approved', approved_by = $2, approved_at = now()
 WHERE id = $1 AND status = 'pending'
RETURNING id, tenant_id, status, requested_by, requested_at, request_reason, approved_by, approved_at, cancelled_by, cancelled_at, executed_at, failure_reason, tenant_name, tenant_slug
`

type ApproveTenantPurgeRequestParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) ApproveTenantPurgeRequest(ctx context.Context, arg ApproveTenantPurgeRequestParams) (TenantPurgeRequest, error) {
	row := q.db.QueryRow(ctx, approveTenantPurgeRequest, arg.ID, arg.ApprovedBy)
	var i TenantPurgeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.RequestReason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.ExecutedAt,
		&i.FailureReason,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_id, project_id, assigned_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, role_id, COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid))
DO NOTHING
`

type AssignRoleParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	ProjectID  pgtype.UUID `json:"project_id"`
	AssignedBy uuid.UUID   `json:"assigned_by"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole,
		arg.UserID,
		arg.RoleID,
		arg.ProjectID,
		arg.AssignedBy,
	)
	return err
}

const cancelTenantPurgeRequest = `-- name: CancelTenantPurgeRequest :one
UPDATE tenant_purge_requests
   SET status = 'cancelled', cancelled_by = $2, cancelled_at = now()
 WHERE id = $1 AND status IN ('pending', 'approved')
RETURNING id, tenant_id, status, requested_by, requested_at, request_reason, approved_by, approved_at, cancelled_by, cancelled_at, executed_at, failure_reason, tenant_name, tenant_slug
`

type CancelTenantPurgeRequestParams struct {
	ID          uuid.UUID   `json:"id"`
	CancelledBy pgtype.UUID `json:"cancelled_by"`
}

func (q *Queries) CancelTenantPurgeRequest(ctx context.Context, arg CancelTenantPurgeRequestParams) (TenantPurgeRequest, error) {
	row := q.db.QueryRow(ctx, cancelTenantPurgeRequest, arg.ID, arg.CancelledBy)
	var i TenantPurgeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.RequestReason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.ExecutedAt,
		&i.FailureReason,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const clearTenantLegalHold = `-- name: ClearTenantLegalHold :one
UPDATE tenants SET
    hold_until    = NULL,
    freeze_reason = NULL
WHERE id = $1
RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at
`

// Unconditionally clears the two legal-hold columns on a tenant,
// releasing the retention-sweeper pause applied via SuspendTenant
// with hold_until/freeze_reason (#92 Stage 4 pair). The tenant's
// status is NOT touched — whatever state it was in (typically
// 'suspended') is preserved and the sweeper's normal lifecycle
// clock resumes on the next run.
//
// Idempotent: running on a tenant with no hold is a no-op UPDATE
// that still returns the row. Callers decide whether to treat the
// no-op as "already cleared" (no audit event) vs. "cleared now".
func (q *Queries) ClearTenantLegalHold(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, clearTenantLegalHold, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const countTenantsOnHold = `-- name: CountTenantsOnHold :one
SELECT COUNT(*) FROM tenants WHERE freeze_reason IS NOT NULL
`

// Counts tenants currently on legal hold (#92 Stage 5). Used by the
// retention sweeper to export a thittam_retention_tenants_on_hold
// gauge per run. Counts ALL tenants with freeze_reason set,
// regardless of status — an 'active' tenant under a precautionary
// hold is still a held tenant.
func (q *Queries) CountTenantsOnHold(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantsOnHold)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (id, tenant_id, email, invited_by, token, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, email) DO UPDATE
    SET token = EXCLUDED.token, expires_at = EXCLUDED.expires_at, accepted_at = NULL
RETURNING id, tenant_id, email, role_id, token, status, invited_by, expires_at, created_at
`

type CreateInvitationParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	Email     string    `json:"email"`
	InvitedBy uuid.UUID `json:"invited_by"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.InvitedBy,
		arg.Token,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.RoleID,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, tenant_id, name, permissions, is_system)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, name) DO NOTHING
RETURNING id, tenant_id, name, permissions, is_system
`

type CreateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
	IsSystem    bool      `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Permissions,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Permissions,
		&i.IsSystem,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (
    id, name, slug, plan, status,
    address_line1, address_line2, city, country_code, postal_code, primary_currency_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (slug) DO NOTHING
RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at
`

type CreateTenantParams struct {
	ID                  uuid.UUID   `json:"id"`
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	Plan                string      `json:"plan"`
	Status              string      `json:"status"`
	AddressLine1        pgtype.Text `json:"address_line1"`
	AddressLine2        pgtype.Text `json:"address_line2"`
	City                pgtype.Text `json:"city"`
	CountryCode         string      `json:"country_code"`
	PostalCode          pgtype.Text `json:"postal_code"`
	PrimaryCurrencyCode string      `json:"primary_currency_code"`
}

// IAM service queries.
// tenants, users, roles, user_roles, invitations live in the shared (public) schema.
// platform_users is the internal admin user table.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.Status,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.CountryCode,
		arg.PostalCode,
		arg.PrimaryCurrencyCode,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const createTenantPurgeRequest = `-- name: CreateTenantPurgeRequest :one
INSERT INTO tenant_purge_requests (
    id, tenant_id, status, requested_by, request_reason, tenant_name, tenant_slug
) VALUES ($1, $2, 'pending', $3, $4, $5, $6)
RETURNING id, tenant_id, status, requested_by, requested_at, request_reason, approved_by, approved_at, cancelled_by, cancelled_at, executed_at, failure_reason, tenant_name, tenant_slug
`

type CreateTenantPurgeRequestParams struct {
	ID            uuid.UUID `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	RequestedBy   uuid.UUID `json:"requested_by"`
	RequestReason string    `json:"request_reason"`
	TenantName    string    `json:"tenant_name"`
	TenantSlug    string    `json:"tenant_slug"`
}

func (q *Queries) CreateTenantPurgeRequest(ctx context.Context, arg CreateTenantPurgeRequestParams) (TenantPurgeRequest, error) {
	row := q.db.QueryRow(ctx, createTenantPurgeRequest,
		arg.ID,
		arg.TenantID,
		arg.RequestedBy,
		arg.RequestReason,
		arg.TenantName,
		arg.TenantSlug,
	)
	var i TenantPurgeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.RequestReason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.ExecutedAt,
		&i.FailureReason,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, email, display_name, password_hash, status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, email) DO NOTHING
RETURNING id, tenant_id, email, display_name, password_hash, status, created_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const findTenantByNormalizedName = `-- name: FindTenantByNormalizedName :one
SELECT id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at FROM tenants
WHERE regexp_replace(lower(trim(name)), '\s+', ' ', 'g')
    = regexp_replace(lower(trim($1)), '\s+', ' ', 'g')
LIMIT 1
`

// Look up a tenant by name under the migration-018 normalisation
// (case-insensitive, trimmed, internal whitespace collapsed). Uses the
// tenants_name_ci_unique index. Powers the pre-flight duplicate check.
func (q *Queries) FindTenantByNormalizedName(ctx context.Context, btrim string) (Tenant, error) {
	row := q.db.QueryRow(ctx, findTenantByNormalizedName, btrim)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, tenant_id, email, role_id, token, status, invited_by, expires_at, created_at FROM invitations
WHERE token = $1 AND accepted_at IS NULL AND expires_at > now()
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.RoleID,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenTenantPurgeRequest = `-- name: GetOpenTenantPurgeRequest :one
SELECT id, tenant_id, status, requested_by, requested_at, request_reason, approved_by, approved_at, cancelled_by, cancelled_at, executed_at, failure_reason, tenant_name, tenant_slug FROM tenant_purge_requests
WHERE tenant_id = $1 AND status IN ('pending', 'approved')
LIMIT 1
`

func (q *Queries) GetOpenTenantPurgeRequest(ctx context.Context, tenantID uuid.UUID) (TenantPurgeRequest, error) {
	row := q.db.QueryRow(ctx, getOpenTenantPurgeRequest, tenantID)
	var i TenantPurgeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.RequestReason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.ExecutedAt,
		&i.FailureReason,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, tenant_id, email, display_name, password_hash, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, display_name, password_hash, status, created_at FROM users WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Email    string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedTenantPurgeRequests = `-- name: ListApprovedTenantPurgeRequests :many
SELECT id, tenant_id, status, requested_by, requested_at, request_reason, approved_by, approved_at, cancelled_by, cancelled_at, executed_at, failure_reason, tenant_name, tenant_slug FROM tenant_purge_requests
 WHERE status = 'approved'
 ORDER BY approved_at
 LIMIT $1
`

func (q *Queries) ListApprovedTenantPurgeRequests(ctx context.Context, limit int32) ([]TenantPurgeRequest, error) {
	rows, err := q.db.Query(ctx, listApprovedTenantPurgeRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantPurgeRequest{}
	for rows.Next() {
		var i TenantPurgeRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Status,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.RequestReason,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CancelledBy,
			&i.CancelledAt,
			&i.ExecutedAt,
			&i.FailureReason,
			&i.TenantName,
			&i.TenantSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, permissions, is_system FROM roles WHERE tenant_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Permissions,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsDueForLifecycle = `-- name: ListTenantsDueForLifecycle :many
SELECT id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at FROM tenants
 WHERE ((status = 'suspended'   AND suspended_at   <= $1::timestamptz - INTERVAL '30 days')
     OR (status = 'grace'       AND suspended_at   <= $1::timestamptz - INTERVAL '90 days')
     OR (status = 'deactivated' AND deactivated_at <= $1::timestamptz - INTERVAL '180 days'))
   AND (freeze_reason IS NULL
        OR (hold_until IS NOT NULL AND hold_until <= $1::timestamptz))
 ORDER BY COALESCE(deactivated_at, suspended_at) NULLS LAST
 LIMIT $2
`

type ListTenantsDueForLifecycleParams struct {
	Column1 time.Time `json:"column_1"`
	Limit   int32     `json:"limit"`
}

// Surfaces tenants whose next automatic lifecycle transition is due at or
// before @now (the sweeper's "now"). Each WHERE branch is backed by a
// partial index created in migration 016, so the query is cheap even
// with many active tenants.
//
// Legal-hold filter (#92 Stage 4): a tenant with freeze_reason set is on
// legal hold. An indefinite hold (hold_until NULL) pins the tenant in its
// current state forever; a time-bounded hold releases once hold_until has
// passed. Active holds are filtered out here so the sweeper never
// advances a tenant under litigation / regulatory freeze.
//
// @now is cast to timestamptz explicitly. Without the cast, the parser
// saw @now used both as `@now - INTERVAL` (where it could be interval)
// and as `hold_until <= @now` (where it must be timestamptz) and failed
// to unify — sqlc then emits interface{} for the param and Postgres
// rejects the timestamp-compare at runtime.
func (q *Queries) ListTenantsDueForLifecycle(ctx context.Context, arg ListTenantsDueForLifecycleParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsDueForLifecycle, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.Status,
			&i.CreatedAt,
			&i.IsDemo,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.CountryCode,
			&i.PostalCode,
			&i.PrimaryCurrencyCode,
			&i.SuspendedAt,
			&i.DeactivatedAt,
			&i.HoldUntil,
			&i.FreezeReason,
			&i.PurgedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.tenant_id, r.name, r.permissions, r.is_system
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Permissions,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, email, display_name, password_hash, status, created_at FROM users
WHERE tenant_id = $1 AND ($2 = '' OR status = $2)
ORDER BY display_name ASC
LIMIT $3 OFFSET $4
`

type ListUsersParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTenantPurgeRequestFailed = `-- name: MarkTenantPurgeRequestFailed :one
UPDATE tenant_purge_requests
   SET status = 'failed', failure_reason = $2
 WHERE id = $1 AND status = 'approved'
RETURNING id, tenant_id, status, requested_by, requested_at, request_reason, approved_by, approved_at, cancelled_by, cancelled_at, executed_at, failure_reason, tenant_name, tenant_slug
`

type MarkTenantPurgeRequestFailedParams struct {
	ID            uuid.UUID   `json:"id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

// Status-guarded so an ambiguous commit (server commits the purge tx,
// client sees a network error and retries the mark-failed call) can never
// clobber a request that actually reached 'executed'. Zero rows means the
// request already left 'approved' — either it executed, or it was
// cancelled mid-flight — and the caller (PurgeApprovedTenant) treats that
// as a benign reconcile, not a failure.
func (q *Queries) MarkTenantPurgeRequestFailed(ctx context.Context, arg MarkTenantPurgeRequestFailedParams) (TenantPurgeRequest, error) {
	row := q.db.QueryRow(ctx, markTenantPurgeRequestFailed, arg.ID, arg.FailureReason)
	var i TenantPurgeRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.RequestReason,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.ExecutedAt,
		&i.FailureReason,
		&i.TenantName,
		&i.TenantSlug,
	)
	return i, err
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2
`

type RevokeRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.UserID, arg.RoleID)
	return err
}

const setTenantLegalHold = `-- name: SetTenantLegalHold :one
UPDATE tenants SET
    hold_until    = $2,
    freeze_reason = $3
WHERE id = $1
RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at
`

type SetTenantLegalHoldParams struct {
	ID           uuid.UUID          `json:"id"`
	HoldUntil    pgtype.Timestamptz `json:"hold_until"`
	FreezeReason pgtype.Text        `json:"freeze_reason"`
}

// Sets the two legal-hold columns on a tenant WITHOUT touching status or the
// suspended_at/deactivated_at anchors — the operator override that pauses or
// extends the retention sweeper for an already-suspended tenant (#119).
// Unlike ClearTenantLegalHold this writes the columns: a NULL hold_until is an
// indefinite hold, a future hold_until is a dated extension. Collision and
// status-eligibility are enforced in the service layer, not here.
func (q *Queries) SetTenantLegalHold(ctx context.Context, arg SetTenantLegalHoldParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantLegalHold, arg.ID, arg.HoldUntil, arg.FreezeReason)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const transitionTenantStatus = `-- name: TransitionTenantStatus :one
UPDATE tenants SET
    status         = $1,
    suspended_at   = CASE WHEN $1::text = 'suspended'   AND suspended_at   IS NULL THEN now() ELSE suspended_at   END,
    deactivated_at = CASE WHEN $1::text = 'deactivated' AND deactivated_at IS NULL THEN now() ELSE deactivated_at END
WHERE id = $2 AND status = $3
RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at
`

type TransitionTenantStatusParams struct {
	ToStatus   string    `json:"to_status"`
	ID         uuid.UUID `json:"id"`
	FromStatus string    `json:"from_status"`
}

// Idempotent lifecycle transition for the retention sweeper. The WHERE
// clause guards against concurrent sweepers double-advancing a tenant;
// callers that get ID = uuid.Nil in the returned row know someone else
// moved the tenant first (#92).
func (q *Queries) TransitionTenantStatus(ctx context.Context, arg TransitionTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, transitionTenantStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const updateTenantAddress = `-- name: UpdateTenantAddress :one
UPDATE tenants SET
    address_line1 = $2,
    address_line2 = $3,
    city = $4,
    country_code = $5,
    postal_code = $6,
    primary_currency_code = $7
WHERE id = $1
RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at
`

type UpdateTenantAddressParams struct {
	ID                  uuid.UUID   `json:"id"`
	AddressLine1        pgtype.Text `json:"address_line1"`
	AddressLine2        pgtype.Text `json:"address_line2"`
	City                pgtype.Text `json:"city"`
	CountryCode         string      `json:"country_code"`
	PostalCode          pgtype.Text `json:"postal_code"`
	PrimaryCurrencyCode string      `json:"primary_currency_code"`
}

func (q *Queries) UpdateTenantAddress(ctx context.Context, arg UpdateTenantAddressParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantAddress,
		arg.ID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.CountryCode,
		arg.PostalCode,
		arg.PrimaryCurrencyCode,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants SET
    status         = $1::text,
    suspended_at   = CASE WHEN $1::text = 'suspended'   AND suspended_at   IS NULL THEN now() ELSE suspended_at   END,
    deactivated_at = CASE WHEN $1::text = 'deactivated' AND deactivated_at IS NULL THEN now() ELSE deactivated_at END,
    hold_until     = COALESCE($2,    hold_until),
    freeze_reason  = COALESCE($3, freeze_reason)
WHERE id = $4
RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason, purged_at
`

type UpdateTenantStatusParams struct {
	Status       string             `json:"status"`
	HoldUntil    pgtype.Timestamptz `json:"hold_until"`
	FreezeReason pgtype.Text        `json:"freeze_reason"`
	ID           uuid.UUID          `json:"id"`
}

// Sets the tenant's status and stamps the appropriate lifecycle timestamp
// on first entry (#92). Repeat calls preserve the original timestamp so
// the grace / deactivation clocks keep ticking from the real transition.
//
// Legal-hold columns (#92 Stage 4) use COALESCE so SuspendTenant callers
// that don't supply hold fields do not clobber an active hold. Clearing
// a hold is a separate admin operation (not in this RPC).
func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus,
		arg.Status,
		arg.HoldUntil,
		arg.FreezeReason,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
		&i.PurgedAt,
	)
	return i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordHashParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2 WHERE id = $1 AND tenant_id = $3 RETURNING id, tenant_id, email, display_name, password_hash, status, created_at
`

type UpdateUserStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
