"""Render a validated company + vertical into ordered, idempotent seed SQL.

Output files (applied in name order with ``psql -v ON_ERROR_STOP=1``):

==================  ==========================================================
``001_tenant.sql``  ``tenants`` row, ``tenant_verticals`` binding, 7 system roles
``002_admin.sql``   first user + tenant-wide ``super_admin`` grant
``003_products.sql`` one ``productions`` row per product
``004_ledger.sql``  chart of accounts (from the vertical) + open periods
==================  ==========================================================

Every statement is safe to re-run: inserts use ``ON CONFLICT ... DO NOTHING``
and each file runs in a single transaction. The admin password hash is never
written into the files; it is supplied at apply time as the psql variable
``admin_password_hash`` and checked for bcrypt shape before use.
"""

from __future__ import annotations

from pathlib import Path

from . import sql
from .company import Company
from .errors import OutputError
from .vertical import Vertical

# Mirrors iam.Service.seedSystemRoles and seeds/template/new-tenant/001_tenant.sql.
# tests/test_repo_drift.py fails if this drifts from the template.
SYSTEM_ROLES: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("super_admin", (
        "production:read", "production:write",
        "budget:read", "budget:write", "budget:approve",
        "expense:read", "expense:submit", "expense:approve",
        "inventory:read", "inventory:checkout",
        "report:read",
        "user:manage",
        "billing:read", "billing:manage",
        "document:read", "document:write", "document:delete",
        "notifications:read", "notifications:manage",
    )),
    ("manager", (
        "production:read", "production:write",
        "budget:read", "budget:approve",
        "expense:read", "expense:approve",
        "inventory:read", "inventory:checkout",
        "report:read",
        "billing:read", "billing:manage",
        "document:read", "document:write", "document:delete",
        "notifications:read", "notifications:manage",
    )),
    ("coordinator", (
        "production:read", "production:write",
        "budget:read", "budget:write",
        "expense:read", "expense:approve",
        "inventory:read", "inventory:checkout",
        "report:read",
        "document:read", "document:write",
    )),
    ("accountant", (
        "budget:read",
        "expense:read", "expense:submit", "expense:approve",
        "report:read",
        "billing:read",
        "document:read", "document:write",
    )),
    ("member", (
        "production:read",
        "expense:submit",
        "document:read",
    )),
    ("inventory_manager", (
        "inventory:read", "inventory:write",
        "inventory:checkout", "inventory:retire",
        "document:read",
    )),
    ("project_supervisor", (
        "production:read",
        "budget:read",
        "expense:read", "expense:submit", "expense:approve",
        "resource:manage",
        "inventory:read", "inventory:checkout",
        "document:read", "document:write",
    )),
)

_BCRYPT_RE = r"^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$"


def _header(company: Company, purpose: str) -> str:
    return (
        f"-- GENERATED by tools/tenant-onboard for {company.name} ({company.slug}).\n"
        "-- Do not edit: change company.yaml / company.local.yaml and regenerate.\n"
        f"-- {purpose}\n"
        "\\set ON_ERROR_STOP on\n\n"
        "BEGIN;\n\n"
    )


def render_tenant(company: Company) -> str:
    """Render ``001_tenant.sql``: tenant row, vertical binding, system roles."""
    t = sql.uuid_lit(company.tenant_id)
    a = company.address
    parts = [
        _header(company, "Tenant row, vertical binding and system roles."),
        "INSERT INTO tenants (\n"
        "    id, name, slug, plan, status,\n"
        "    address_line1, address_line2, city, country_code, postal_code,\n"
        "    primary_currency_code, is_demo\n"
        ") VALUES (\n"
        f"    {t}, {sql.text(company.name)}, {sql.text(company.slug)}, {sql.text(company.plan)}, 'active',\n"
        f"    {sql.text(a.line1)}, {sql.text(a.line2)}, {sql.text(a.city)}, {sql.text(a.country)}, {sql.text(a.postal_code)},\n"
        f"    {sql.text(company.currency)}, false\n"
        ")\nON CONFLICT (id) DO NOTHING;\n\n",
        "INSERT INTO tenant_verticals (tenant_id, vertical_id, registered_by)\n"
        f"VALUES ({t}, {sql.text(company.vertical_id)}, {sql.uuid_lit(company.admin.id)})\n"
        "ON CONFLICT (tenant_id) DO NOTHING;\n\n",
        "INSERT INTO roles (tenant_id, name, permissions, is_system) VALUES\n",
        ",\n".join(f"    ({t}, {sql.text(name)}, {sql.text_array(list(perms))}, true)"
                   for name, perms in SYSTEM_ROLES),
        "\nON CONFLICT (tenant_id, name) DO NOTHING;\n\nCOMMIT;\n",
    ]
    return "".join(parts)


def render_admin(company: Company) -> str:
    """Render ``002_admin.sql``; requires psql var ``admin_password_hash``."""
    t = sql.uuid_lit(company.tenant_id)
    u = sql.uuid_lit(company.admin.id)
    guard = (
        f"-- GENERATED by tools/tenant-onboard for {company.name} ({company.slug}).\n"
        "-- First admin user. Apply with:\n"
        "--   psql \"$DB_URL\" -v admin_password_hash='<bcrypt hash>' -f 002_admin.sql\n"
        "\\set ON_ERROR_STOP on\n\n"
        "\\if :{?admin_password_hash}\n"
        "\\else\n"
        "  \\echo 'ERROR: missing -v admin_password_hash=<bcrypt hash>. Generate one with:'\n"
        "  \\echo '  python3 -m tenant_onboard hash-password'\n"
        "  DO $$ BEGIN RAISE EXCEPTION 'admin_password_hash not supplied'; END $$;\n"
        "\\endif\n\n"
        f"SELECT (:'admin_password_hash' ~ {sql.text(_BCRYPT_RE)}) AS admin_hash_ok \\gset\n"
        "\\if :admin_hash_ok\n"
        "\\else\n"
        "  DO $$ BEGIN RAISE EXCEPTION 'admin_password_hash is not a bcrypt hash'; END $$;\n"
        "\\endif\n\n"
        "BEGIN;\n\n"
    )
    body = (
        "INSERT INTO users (id, tenant_id, email, display_name, password_hash, status)\n"
        f"VALUES ({u}, {t}, {sql.text(company.admin.email)}, {sql.text(company.admin.display_name)},\n"
        "        :'admin_password_hash', 'active')\n"
        "ON CONFLICT (id) DO NOTHING;\n\n"
        "INSERT INTO user_roles (user_id, role_id, project_id, assigned_by)\n"
        f"SELECT {u}, r.id, NULL, {u}\n"
        "  FROM roles r\n"
        f" WHERE r.tenant_id = {t}\n"
        "   AND r.name      = 'super_admin'\n"
        "-- Conflict target matches the user_roles_unique expression index (iam migration 012).\n"
        "ON CONFLICT (user_id, role_id, COALESCE(project_id, '00000000-0000-0000-0000-000000000000'::uuid)) DO NOTHING;\n\n"
        "-- Fail loudly if the role was not found (001_tenant.sql not applied).\n"
        "DO $$\nBEGIN\n"
        "  IF NOT EXISTS (\n"
        "      SELECT 1 FROM user_roles ur JOIN roles r ON r.id = ur.role_id\n"
        f"       WHERE ur.user_id = {u} AND r.name = 'super_admin') THEN\n"
        "    RAISE EXCEPTION 'super_admin grant missing: apply 001_tenant.sql first';\n"
        "  END IF;\nEND $$;\n\nCOMMIT;\n"
    )
    return guard + body


def render_products(company: Company) -> str:
    """Render ``003_products.sql``: one ``productions`` row per product."""
    t = sql.uuid_lit(company.tenant_id)
    u = sql.uuid_lit(company.admin.id)
    rows = []
    for p in company.products:
        rows.append(
            f"-- {p.title} — stage {p.stage!s} → status {company.status_for(p.stage)}\n"
            "INSERT INTO productions (tenant_id, title, slug, description, status, start_date, end_date, created_by)\n"
            f"VALUES ({t}, {sql.text(p.title)}, {sql.text(p.slug)}, {sql.text(p.description)},\n"
            f"        {sql.text(company.status_for(p.stage))}, {sql.date_lit(p.start_date)}, {sql.date_lit(p.end_date)}, {u})\n"
            "ON CONFLICT (tenant_id, slug) DO NOTHING;\n"
        )
    return _header(company, "Products (productions rows).") + "\n".join(rows) + "\nCOMMIT;\n"


def render_ledger(company: Company, vertical: Vertical) -> str:
    """Render ``004_ledger.sql``: chart of accounts and open periods.

    Accounts are inserted one statement at a time, parents first, and the
    parent id is resolved by code — so this also works for a tenant whose
    accounts were partly created by the ledger service already.
    """
    t = sql.uuid_lit(company.tenant_id)
    out = [_header(company, f"Chart of accounts from {vertical.id} and open accounting periods.")]
    for acc in vertical.accounts:
        parent = (
            f"(SELECT id FROM accounts WHERE tenant_id = {t} AND code = {sql.text(acc.parent_code)})"
            if acc.parent_code else "NULL"
        )
        out.append(
            "INSERT INTO accounts (tenant_id, code, name, account_type, parent_id, is_active)\n"
            f"VALUES ({t}, {sql.text(acc.code)}, {sql.text(acc.name)}, {sql.text(acc.account_type)}, {parent}, true)\n"
            "ON CONFLICT (tenant_id, code) DO NOTHING;\n"
        )
    out.append(
        f"\n-- Books open {company.books.opening_date.isoformat()}; periods through fiscal year end "
        f"(month {company.books.fiscal_year_end_month}).\n"
        "INSERT INTO accounting_periods (tenant_id, year, month, status) VALUES\n"
        + ",\n".join(f"    ({t}, {sql.integer(y)}, {sql.integer(m)}, 'open')"
                     for y, m in company.books.open_periods())
        + "\nON CONFLICT (tenant_id, year, month) DO NOTHING;\n\nCOMMIT;\n"
    )
    return "".join(out)


def render_all(company: Company, vertical: Vertical) -> dict[str, str]:
    """Render every seed file, keyed by file name in apply order."""
    return {
        "001_tenant.sql": render_tenant(company),
        "002_admin.sql": render_admin(company),
        "003_products.sql": render_products(company),
        "004_ledger.sql": render_ledger(company, vertical),
    }


def write_files(files: dict[str, str], out_dir: str | Path) -> list[Path]:
    """Write rendered files to ``out_dir``, creating it if needed.

    Files are written to a temporary name and renamed, so an interrupted run
    never leaves a half-written ``.sql`` that ``psql`` would apply.

    Returns:
        The written paths in apply order.

    Raises:
        OutputError: If the directory or a file cannot be written.
    """
    d = Path(out_dir)
    try:
        d.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise OutputError(str(d), exc.strerror or str(exc)) from exc
    written: list[Path] = []
    for name in sorted(files):
        target = d / name
        tmp = d / f".{name}.tmp"
        try:
            tmp.write_text(files[name], encoding="utf-8")
            tmp.replace(target)
        except OSError as exc:
            tmp.unlink(missing_ok=True)
            raise OutputError(str(target), exc.strerror or str(exc)) from exc
        written.append(target)
    return written
