// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

// DBTX is the interface satisfied by *sql.DB and *sql.Tx.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// Queries provides all the generated query methods.
type Queries struct {
	db DBTX
}

// New creates a Queries instance backed by a connection or pool.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}
