// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Invitation struct {
	ID        uuid.UUID   `json:"id"`
	TenantID  uuid.UUID   `json:"tenant_id"`
	Email     string      `json:"email"`
	RoleID    pgtype.UUID `json:"role_id"`
	Token     string      `json:"token"`
	Status    string      `json:"status"`
	InvitedBy uuid.UUID   `json:"invited_by"`
	ExpiresAt time.Time   `json:"expires_at"`
	CreatedAt time.Time   `json:"created_at"`
}

type PlatformImpersonationLog struct {
	ID               uuid.UUID          `json:"id"`
	PlatformUserID   uuid.UUID          `json:"platform_user_id"`
	TenantID         uuid.UUID          `json:"tenant_id"`
	ImpersonatedUser uuid.UUID          `json:"impersonated_user"`
	Reason           string             `json:"reason"`
	StartedAt        time.Time          `json:"started_at"`
	ExpiresAt        time.Time          `json:"expires_at"`
	IpAddress        pgtype.Text        `json:"ip_address"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
}

type PlatformUser struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	MfaSecret    pgtype.Text        `json:"mfa_secret"`
	MfaEnabled   bool               `json:"mfa_enabled"`
	Status       string             `json:"status"`
	CreatedAt    time.Time          `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

type RegistrationSaga struct {
	ID                 uuid.UUID   `json:"id"`
	Email              string      `json:"email"`
	TenantID           pgtype.UUID `json:"tenant_id"`
	UserID             pgtype.UUID `json:"user_id"`
	Status             string      `json:"status"`
	CompletedSteps     []byte      `json:"completed_steps"`
	FailedStep         pgtype.Text `json:"failed_step"`
	FailureReason      pgtype.Text `json:"failure_reason"`
	CompensationErrors []byte      `json:"compensation_errors"`
	Request            []byte      `json:"request"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
	IsSystem    bool      `json:"is_system"`
}

type Tenant struct {
	ID                  uuid.UUID   `json:"id"`
	Name                string      `json:"name"`
	Slug                string      `json:"slug"`
	Plan                string      `json:"plan"`
	Status              string      `json:"status"`
	CreatedAt           time.Time   `json:"created_at"`
	IsDemo              bool        `json:"is_demo"`
	AddressLine1        pgtype.Text `json:"address_line1"`
	AddressLine2        pgtype.Text `json:"address_line2"`
	City                pgtype.Text `json:"city"`
	CountryCode         string      `json:"country_code"`
	PostalCode          pgtype.Text `json:"postal_code"`
	PrimaryCurrencyCode string      `json:"primary_currency_code"`
}

type TenantAuthConfig struct {
	TenantID         uuid.UUID   `json:"tenant_id"`
	AuthMethod       string      `json:"auth_method"`
	IssuerUrl        pgtype.Text `json:"issuer_url"`
	ClientID         pgtype.Text `json:"client_id"`
	ClientSecretEnc  pgtype.Text `json:"client_secret_enc"`
	Scopes           []string    `json:"scopes"`
	EmailClaim       string      `json:"email_claim"`
	DisplayNameClaim string      `json:"display_name_claim"`
	GroupsClaim      pgtype.Text `json:"groups_claim"`
	AutoProvision    bool        `json:"auto_provision"`
	DefaultRole      string      `json:"default_role"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type TenantSetting struct {
	TenantID      uuid.UUID   `json:"tenant_id"`
	ThemeOverride []byte      `json:"theme_override"`
	LogoUrl       pgtype.Text `json:"logo_url"`
	FaviconUrl    pgtype.Text `json:"favicon_url"`
	UpdatedAt     time.Time   `json:"updated_at"`
	UpdatedBy     pgtype.UUID `json:"updated_by"`
}

type TenantVertical struct {
	TenantID       uuid.UUID `json:"tenant_id"`
	VerticalID     string    `json:"vertical_id"`
	ConfigOverride []byte    `json:"config_override"`
	RegisteredAt   time.Time `json:"registered_at"`
	RegisteredBy   uuid.UUID `json:"registered_by"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserRole struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	AssignedBy uuid.UUID   `json:"assigned_by"`
	AssignedAt time.Time   `json:"assigned_at"`
	ProjectID  pgtype.UUID `json:"project_id"`
}

type VerticalDefinition struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Version     string      `json:"version"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	IsActive    bool        `json:"is_active"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
