// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, plan) VALUES ($1, $2, $3) RETURNING id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason
`

type CreateTenantParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	Plan string `json:"plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Slug, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, display_name, password_hash)
VALUES ($1, $2, $3, $4) RETURNING id, tenant_id, email, display_name, password_hash, status, created_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `json:"tenant_id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, plan, status, created_at, is_demo, address_line1, address_line2, city, country_code, postal_code, primary_currency_code, suspended_at, deactivated_at, hold_until, freeze_reason FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.Status,
		&i.CreatedAt,
		&i.IsDemo,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.CountryCode,
		&i.PostalCode,
		&i.PrimaryCurrencyCode,
		&i.SuspendedAt,
		&i.DeactivatedAt,
		&i.HoldUntil,
		&i.FreezeReason,
	)
	return i, err
}

const tenantExistsByNormalizedName = `-- name: TenantExistsByNormalizedName :one
SELECT EXISTS (
    SELECT 1 FROM tenants
    WHERE regexp_replace(lower(trim(name)), '\s+', ' ', 'g')
        = regexp_replace(lower(trim($1)), '\s+', ' ', 'g')
)
`

func (q *Queries) TenantExistsByNormalizedName(ctx context.Context, btrim string) (bool, error) {
	row := q.db.QueryRow(ctx, tenantExistsByNormalizedName, btrim)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const tenantExistsBySlug = `-- name: TenantExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM tenants WHERE slug = $1)
`

func (q *Queries) TenantExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, tenantExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
