// Code generated by sqlc. DO NOT EDIT.
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, slug, plan) VALUES ($1, $2, $3)
RETURNING id, name, slug, plan, status, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name, slug, plan string) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant, name, slug, plan)
	var t Tenant
	err := row.Scan(&t.ID, &t.Name, &t.Slug, &t.Plan, &t.Status, &t.CreatedAt)
	return t, err
}

const tenantExistsBySlug = `-- name: TenantExistsBySlug :one
SELECT EXISTS(SELECT 1 FROM tenants WHERE slug = $1)
`

func (q *Queries) TenantExistsBySlug(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRowContext(ctx, tenantExistsBySlug, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, display_name, password_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, email, display_name, password_hash, status, created_at
`

func (q *Queries) CreateUser(ctx context.Context, tenantID uuid.UUID, email, displayName, passwordHash string) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, tenantID, email, displayName, passwordHash)
	var u User
	err := row.Scan(&u.ID, &u.TenantID, &u.Email, &u.DisplayName, &u.PasswordHash, &u.Status, &u.CreatedAt)
	return u, err
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, plan, status, created_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var t Tenant
	err := row.Scan(&t.ID, &t.Name, &t.Slug, &t.Plan, &t.Status, &t.CreatedAt)
	return t, err
}
