// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationLog struct {
	ID            uuid.UUID          `json:"id"`
	TenantID      uuid.UUID          `json:"tenant_id"`
	RecipientID   uuid.UUID          `json:"recipient_id"`
	Channel       string             `json:"channel"`
	EventType     string             `json:"event_type"`
	Subject       pgtype.Text        `json:"subject"`
	ProviderMsgID pgtype.Text        `json:"provider_msg_id"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	SentAt        pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt     time.Time          `json:"created_at"`
}

type NotificationTemplate struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	EventType    string      `json:"event_type"`
	Channel      string      `json:"channel"`
	Subject      pgtype.Text `json:"subject"`
	BodyTemplate string      `json:"body_template"`
	IsActive     bool        `json:"is_active"`
}
