// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotificationLog = `-- name: CreateNotificationLog :one
INSERT INTO notification_log (id, tenant_id, recipient_id, channel, event_type, subject, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
ON CONFLICT (id) DO NOTHING
RETURNING id, tenant_id, recipient_id, channel, event_type, subject, provider_msg_id, status, retry_count, error_message, sent_at, delivered_at, created_at
`

type CreateNotificationLogParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	RecipientID uuid.UUID   `json:"recipient_id"`
	Channel     string      `json:"channel"`
	EventType   string      `json:"event_type"`
	Subject     pgtype.Text `json:"subject"`
}

func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (NotificationLog, error) {
	row := q.db.QueryRow(ctx, createNotificationLog,
		arg.ID,
		arg.TenantID,
		arg.RecipientID,
		arg.Channel,
		arg.EventType,
		arg.Subject,
	)
	var i NotificationLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RecipientID,
		&i.Channel,
		&i.EventType,
		&i.Subject,
		&i.ProviderMsgID,
		&i.Status,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.SentAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplate = `-- name: GetTemplate :one

SELECT id, tenant_id, event_type, channel, subject, body_template, is_active FROM notification_templates
WHERE tenant_id = $1 AND event_type = $2 AND channel = $3 AND is_active = true
`

type GetTemplateParams struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	EventType string    `json:"event_type"`
	Channel   string    `json:"channel"`
}

// Notifications service queries.
func (q *Queries) GetTemplate(ctx context.Context, arg GetTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplate, arg.TenantID, arg.EventType, arg.Channel)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Channel,
		&i.Subject,
		&i.BodyTemplate,
		&i.IsActive,
	)
	return i, err
}

const listNotificationLog = `-- name: ListNotificationLog :many
SELECT id, tenant_id, recipient_id, channel, event_type, subject, provider_msg_id, status, retry_count, error_message, sent_at, delivered_at, created_at FROM notification_log
WHERE tenant_id = $1 AND ($2::uuid IS NULL OR recipient_id = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotificationLogParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Column2  uuid.UUID `json:"column_2"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListNotificationLog(ctx context.Context, arg ListNotificationLogParams) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listNotificationLog,
		arg.TenantID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RecipientID,
			&i.Channel,
			&i.EventType,
			&i.Subject,
			&i.ProviderMsgID,
			&i.Status,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotifications = `-- name: ListPendingNotifications :many
SELECT id, tenant_id, recipient_id, channel, event_type, subject, provider_msg_id, status, retry_count, error_message, sent_at, delivered_at, created_at FROM notification_log
WHERE status = 'pending' AND retry_count < 4
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingNotifications(ctx context.Context, limit int32) ([]NotificationLog, error) {
	rows, err := q.db.Query(ctx, listPendingNotifications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationLog{}
	for rows.Next() {
		var i NotificationLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.RecipientID,
			&i.Channel,
			&i.EventType,
			&i.Subject,
			&i.ProviderMsgID,
			&i.Status,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.SentAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, tenant_id, event_type, channel, subject, body_template, is_active FROM notification_templates
WHERE tenant_id = $1 AND ($2 = '' OR event_type = $2)
ORDER BY event_type, channel
`

type ListTemplatesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
}

func (q *Queries) ListTemplates(ctx context.Context, arg ListTemplatesParams) ([]NotificationTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationTemplate{}
	for rows.Next() {
		var i NotificationTemplate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.Channel,
			&i.Subject,
			&i.BodyTemplate,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationLogFailed = `-- name: UpdateNotificationLogFailed :exec
UPDATE notification_log
SET status        = 'failed',
    error_message = $2,
    retry_count   = retry_count + 1
WHERE id = $1
`

type UpdateNotificationLogFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateNotificationLogFailed(ctx context.Context, arg UpdateNotificationLogFailedParams) error {
	_, err := q.db.Exec(ctx, updateNotificationLogFailed, arg.ID, arg.ErrorMessage)
	return err
}

const updateNotificationLogSent = `-- name: UpdateNotificationLogSent :exec
UPDATE notification_log
SET status          = 'sent',
    provider_msg_id = $2,
    sent_at         = now()
WHERE id = $1
`

type UpdateNotificationLogSentParams struct {
	ID            uuid.UUID   `json:"id"`
	ProviderMsgID pgtype.Text `json:"provider_msg_id"`
}

func (q *Queries) UpdateNotificationLogSent(ctx context.Context, arg UpdateNotificationLogSentParams) error {
	_, err := q.db.Exec(ctx, updateNotificationLogSent, arg.ID, arg.ProviderMsgID)
	return err
}

const upsertTemplate = `-- name: UpsertTemplate :one
INSERT INTO notification_templates (id, tenant_id, event_type, channel, subject, body_template, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, event_type, channel) DO UPDATE
    SET subject       = EXCLUDED.subject,
        body_template = EXCLUDED.body_template,
        is_active     = EXCLUDED.is_active
RETURNING id, tenant_id, event_type, channel, subject, body_template, is_active
`

type UpsertTemplateParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	EventType    string      `json:"event_type"`
	Channel      string      `json:"channel"`
	Subject      pgtype.Text `json:"subject"`
	BodyTemplate string      `json:"body_template"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpsertTemplate(ctx context.Context, arg UpsertTemplateParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, upsertTemplate,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.Channel,
		arg.Subject,
		arg.BodyTemplate,
		arg.IsActive,
	)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.Channel,
		&i.Subject,
		&i.BodyTemplate,
		&i.IsActive,
	)
	return i, err
}
