-- GENERATED by tools/tenant-onboard from pkg/vertical/configs/software-development-us.yaml
-- Do not edit by hand: change the YAML, then run `make vertical-migrations`.
-- `make check-vertical-migrations` fails CI if this file drifts from the YAML.
--
-- Fails (FK on tenant_verticals) while any tenant is still bound to this
-- vertical. That is intentional: rebind or remove those tenants first.

DELETE FROM vertical_definitions WHERE id = 'software-development-us';
