// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	AccountType string      `json:"account_type"`
	ParentID    pgtype.UUID `json:"parent_id"`
	IsActive    bool        `json:"is_active"`
}

type AccountingPeriod struct {
	ID       uuid.UUID          `json:"id"`
	TenantID uuid.UUID          `json:"tenant_id"`
	Year     int32              `json:"year"`
	Month    int32              `json:"month"`
	Status   string             `json:"status"`
	ClosedBy pgtype.UUID        `json:"closed_by"`
	ClosedAt pgtype.Timestamptz `json:"closed_at"`
}

type JournalEntry struct {
	ID           uuid.UUID          `json:"id"`
	TenantID     uuid.UUID          `json:"tenant_id"`
	ProductionID pgtype.UUID        `json:"production_id"`
	PeriodID     uuid.UUID          `json:"period_id"`
	EntryNumber  string             `json:"entry_number"`
	Reference    pgtype.Text        `json:"reference"`
	Narration    string             `json:"narration"`
	Status       string             `json:"status"`
	PostedBy     pgtype.UUID        `json:"posted_by"`
	PostedAt     pgtype.Timestamptz `json:"posted_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type JournalEntryCounter struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Year     int32     `json:"year"`
	NextSeq  int32     `json:"next_seq"`
}

type JournalLine struct {
	ID           uuid.UUID      `json:"id"`
	JournalID    uuid.UUID      `json:"journal_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	DebitAmount  pgtype.Numeric `json:"debit_amount"`
	CreditAmount pgtype.Numeric `json:"credit_amount"`
	Currency     string         `json:"currency"`
	Description  pgtype.Text    `json:"description"`
}
