// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeAccountingPeriod = `-- name: CloseAccountingPeriod :one
UPDATE accounting_periods SET status = 'closed', closed_at = now(), closed_by = $3
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, year, month, status, closed_by, closed_at
`

type CloseAccountingPeriodParams struct {
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	ClosedBy pgtype.UUID `json:"closed_by"`
}

func (q *Queries) CloseAccountingPeriod(ctx context.Context, arg CloseAccountingPeriodParams) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, closeAccountingPeriod, arg.ID, arg.TenantID, arg.ClosedBy)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one

INSERT INTO accounts (id, tenant_id, code, name, account_type, parent_id, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, code) DO NOTHING
RETURNING id, tenant_id, code, name, account_type, parent_id, is_active
`

type CreateAccountParams struct {
	ID          uuid.UUID   `json:"id"`
	TenantID    uuid.UUID   `json:"tenant_id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	AccountType string      `json:"account_type"`
	ParentID    pgtype.UUID `json:"parent_id"`
	IsActive    bool        `json:"is_active"`
}

// General ledger service queries.
func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.AccountType,
		arg.ParentID,
		arg.IsActive,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const createAccountingPeriod = `-- name: CreateAccountingPeriod :one
INSERT INTO accounting_periods (id, tenant_id, year, month, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
RETURNING id, tenant_id, year, month, status, closed_by, closed_at
`

type CreateAccountingPeriodParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Year     int32     `json:"year"`
	Month    int32     `json:"month"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateAccountingPeriod(ctx context.Context, arg CreateAccountingPeriodParams) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, createAccountingPeriod,
		arg.ID,
		arg.TenantID,
		arg.Year,
		arg.Month,
		arg.Status,
	)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const createJournalEntry = `-- name: CreateJournalEntry :one
INSERT INTO journal_entries (id, tenant_id, production_id, period_id, entry_number, reference, narration, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO NOTHING
RETURNING id, tenant_id, production_id, period_id, entry_number, reference, narration, status, posted_by, posted_at, created_at
`

type CreateJournalEntryParams struct {
	ID           uuid.UUID   `json:"id"`
	TenantID     uuid.UUID   `json:"tenant_id"`
	ProductionID pgtype.UUID `json:"production_id"`
	PeriodID     uuid.UUID   `json:"period_id"`
	EntryNumber  string      `json:"entry_number"`
	Reference    pgtype.Text `json:"reference"`
	Narration    string      `json:"narration"`
	Status       string      `json:"status"`
}

func (q *Queries) CreateJournalEntry(ctx context.Context, arg CreateJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, createJournalEntry,
		arg.ID,
		arg.TenantID,
		arg.ProductionID,
		arg.PeriodID,
		arg.EntryNumber,
		arg.Reference,
		arg.Narration,
		arg.Status,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.Reference,
		&i.Narration,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createJournalLine = `-- name: CreateJournalLine :one
INSERT INTO journal_lines (id, journal_id, account_id, debit_amount, credit_amount, description)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO NOTHING
RETURNING id, journal_id, account_id, debit_amount, credit_amount, currency, description
`

type CreateJournalLineParams struct {
	ID           uuid.UUID      `json:"id"`
	JournalID    uuid.UUID      `json:"journal_id"`
	AccountID    uuid.UUID      `json:"account_id"`
	DebitAmount  pgtype.Numeric `json:"debit_amount"`
	CreditAmount pgtype.Numeric `json:"credit_amount"`
	Description  pgtype.Text    `json:"description"`
}

func (q *Queries) CreateJournalLine(ctx context.Context, arg CreateJournalLineParams) (JournalLine, error) {
	row := q.db.QueryRow(ctx, createJournalLine,
		arg.ID,
		arg.JournalID,
		arg.AccountID,
		arg.DebitAmount,
		arg.CreditAmount,
		arg.Description,
	)
	var i JournalLine
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.AccountID,
		&i.DebitAmount,
		&i.CreditAmount,
		&i.Currency,
		&i.Description,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, tenant_id, code, name, account_type, parent_id, is_active FROM accounts WHERE id = $1 AND tenant_id = $2
`

type GetAccountParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.TenantID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT
    a.id,
    a.code,
    a.name,
    a.account_type,
    COALESCE(SUM(jl.debit_amount),  0) AS total_debits,
    COALESCE(SUM(jl.credit_amount), 0) AS total_credits
FROM accounts a
LEFT JOIN journal_lines jl   ON jl.account_id  = a.id
LEFT JOIN journal_entries je ON je.id = jl.journal_id AND je.status = 'posted'
WHERE a.id = $1 AND a.tenant_id = $2
GROUP BY a.id, a.code, a.name, a.account_type
`

type GetAccountBalanceParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

type GetAccountBalanceRow struct {
	ID           uuid.UUID   `json:"id"`
	Code         string      `json:"code"`
	Name         string      `json:"name"`
	AccountType  string      `json:"account_type"`
	TotalDebits  interface{} `json:"total_debits"`
	TotalCredits interface{} `json:"total_credits"`
}

func (q *Queries) GetAccountBalance(ctx context.Context, arg GetAccountBalanceParams) (GetAccountBalanceRow, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, arg.ID, arg.TenantID)
	var i GetAccountBalanceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.TotalDebits,
		&i.TotalCredits,
	)
	return i, err
}

const getAccountByCode = `-- name: GetAccountByCode :one
SELECT id, tenant_id, code, name, account_type, parent_id, is_active FROM accounts WHERE code = $1 AND tenant_id = $2
`

type GetAccountByCodeParams struct {
	Code     string    `json:"code"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAccountByCode(ctx context.Context, arg GetAccountByCodeParams) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByCode, arg.Code, arg.TenantID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.AccountType,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const getAccountingPeriod = `-- name: GetAccountingPeriod :one
SELECT id, tenant_id, year, month, status, closed_by, closed_at FROM accounting_periods WHERE id = $1 AND tenant_id = $2
`

type GetAccountingPeriodParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAccountingPeriod(ctx context.Context, arg GetAccountingPeriodParams) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, getAccountingPeriod, arg.ID, arg.TenantID)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const getJournalEntry = `-- name: GetJournalEntry :one
SELECT id, tenant_id, production_id, period_id, entry_number, reference, narration, status, posted_by, posted_at, created_at FROM journal_entries WHERE id = $1 AND tenant_id = $2
`

type GetJournalEntryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetJournalEntry(ctx context.Context, arg GetJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, getJournalEntry, arg.ID, arg.TenantID)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.Reference,
		&i.Narration,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenPeriod = `-- name: GetOpenPeriod :one
SELECT id, tenant_id, year, month, status, closed_by, closed_at FROM accounting_periods
WHERE tenant_id = $1 AND status = 'open'
ORDER BY year DESC, month DESC
LIMIT 1
`

func (q *Queries) GetOpenPeriod(ctx context.Context, tenantID uuid.UUID) (AccountingPeriod, error) {
	row := q.db.QueryRow(ctx, getOpenPeriod, tenantID)
	var i AccountingPeriod
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Year,
		&i.Month,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, tenant_id, code, name, account_type, parent_id, is_active FROM accounts
WHERE tenant_id = $1 AND ($2 = '' OR account_type = $2) AND is_active = true
ORDER BY code ASC
LIMIT $3 OFFSET $4
`

type ListAccountsParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  interface{} `json:"column_2"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts, arg.TenantID, arg.Column2, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.AccountType,
			&i.ParentID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, tenant_id, production_id, period_id, entry_number, reference, narration, status, posted_by, posted_at, created_at FROM journal_entries
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR period_id = $2)
  AND ($3 = '' OR status = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListJournalEntriesParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Column2  uuid.UUID   `json:"column_2"`
	Column3  interface{} `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries,
		arg.TenantID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductionID,
			&i.PeriodID,
			&i.EntryNumber,
			&i.Reference,
			&i.Narration,
			&i.Status,
			&i.PostedBy,
			&i.PostedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalLines = `-- name: ListJournalLines :many
SELECT id, journal_id, account_id, debit_amount, credit_amount, currency, description FROM journal_lines WHERE journal_id = $1 ORDER BY id ASC
`

func (q *Queries) ListJournalLines(ctx context.Context, journalID uuid.UUID) ([]JournalLine, error) {
	rows, err := q.db.Query(ctx, listJournalLines, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalLine{}
	for rows.Next() {
		var i JournalLine
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountID,
			&i.DebitAmount,
			&i.CreditAmount,
			&i.Currency,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextJournalEntrySeq = `-- name: NextJournalEntrySeq :one
INSERT INTO journal_entry_counters (tenant_id, year, next_seq)
VALUES ($1, $2, 1)
ON CONFLICT (tenant_id, year) DO UPDATE
    SET next_seq = journal_entry_counters.next_seq + 1
RETURNING next_seq
`

type NextJournalEntrySeqParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Year     int32     `json:"year"`
}

func (q *Queries) NextJournalEntrySeq(ctx context.Context, arg NextJournalEntrySeqParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextJournalEntrySeq, arg.TenantID, arg.Year)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const postJournalEntry = `-- name: PostJournalEntry :one
UPDATE journal_entries SET status = 'posted', posted_by = $3, posted_at = now()
WHERE id = $1 AND tenant_id = $2 AND status = 'draft'
RETURNING id, tenant_id, production_id, period_id, entry_number, reference, narration, status, posted_by, posted_at, created_at
`

type PostJournalEntryParams struct {
	ID       uuid.UUID   `json:"id"`
	TenantID uuid.UUID   `json:"tenant_id"`
	PostedBy pgtype.UUID `json:"posted_by"`
}

func (q *Queries) PostJournalEntry(ctx context.Context, arg PostJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, postJournalEntry, arg.ID, arg.TenantID, arg.PostedBy)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.Reference,
		&i.Narration,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}

const voidJournalEntry = `-- name: VoidJournalEntry :one
UPDATE journal_entries SET status = 'void'
WHERE id = $1 AND tenant_id = $2 AND status = 'posted'
RETURNING id, tenant_id, production_id, period_id, entry_number, reference, narration, status, posted_by, posted_at, created_at
`

type VoidJournalEntryParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) VoidJournalEntry(ctx context.Context, arg VoidJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, voidJournalEntry, arg.ID, arg.TenantID)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductionID,
		&i.PeriodID,
		&i.EntryNumber,
		&i.Reference,
		&i.Narration,
		&i.Status,
		&i.PostedBy,
		&i.PostedAt,
		&i.CreatedAt,
	)
	return i, err
}
